// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/tokenservice/models"
)

// GetTokenReader is a Reader for the GetToken structure.
type GetTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/token/{jti}] GetToken", response, response.Code())
	}
}

// NewGetTokenOK creates a GetTokenOK with default headers values
func NewGetTokenOK() *GetTokenOK {
	return &GetTokenOK{}
}

/*
GetTokenOK describes a response with status code 200, with default header values.

Success.
*/
type GetTokenOK struct {
	Payload *models.TokenDetails
}

// IsSuccess returns true when this get token o k response has a 2xx status code
func (o *GetTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get token o k response has a 3xx status code
func (o *GetTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get token o k response has a 4xx status code
func (o *GetTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get token o k response has a 5xx status code
func (o *GetTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get token o k response a status code equal to that given
func (o *GetTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get token o k response
func (o *GetTokenOK) Code() int {
	return 200
}

func (o *GetTokenOK) Error() string {
	return fmt.Sprintf("[GET /v1/token/{jti}][%d] getTokenOK  %+v", 200, o.Payload)
}

func (o *GetTokenOK) String() string {
	return fmt.Sprintf("[GET /v1/token/{jti}][%d] getTokenOK  %+v", 200, o.Payload)
}

func (o *GetTokenOK) GetPayload() *models.TokenDetails {
	return o.Payload
}

func (o *GetTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TokenDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokenForbidden creates a GetTokenForbidden with default headers values
func NewGetTokenForbidden() *GetTokenForbidden {
	return &GetTokenForbidden{}
}

/*
GetTokenForbidden describes a response with status code 403, with default header values.

Forbidden. Authorization token was not supplied, not valid, or revoked.
*/
type GetTokenForbidden struct {
}

// IsSuccess returns true when this get token forbidden response has a 2xx status code
func (o *GetTokenForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get token forbidden response has a 3xx status code
func (o *GetTokenForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get token forbidden response has a 4xx status code
func (o *GetTokenForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get token forbidden response has a 5xx status code
func (o *GetTokenForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get token forbidden response a status code equal to that given
func (o *GetTokenForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get token forbidden response
func (o *GetTokenForbidden) Code() int {
	return 403
}

func (o *GetTokenForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/token/{jti}][%d] getTokenForbidden ", 403)
}

func (o *GetTokenForbidden) String() string {
	return fmt.Sprintf("[GET /v1/token/{jti}][%d] getTokenForbidden ", 403)
}

func (o *GetTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTokenInternalServerError creates a GetTokenInternalServerError with default headers values
func NewGetTokenInternalServerError() *GetTokenInternalServerError {
	return &GetTokenInternalServerError{}
}

/*
GetTokenInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetTokenInternalServerError struct {
}

// IsSuccess returns true when this get token internal server error response has a 2xx status code
func (o *GetTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get token internal server error response has a 3xx status code
func (o *GetTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get token internal server error response has a 4xx status code
func (o *GetTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get token internal server error response has a 5xx status code
func (o *GetTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get token internal server error response a status code equal to that given
func (o *GetTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get token internal server error response
func (o *GetTokenInternalServerError) Code() int {
	return 500
}

func (o *GetTokenInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/token/{jti}][%d] getTokenInternalServerError ", 500)
}

func (o *GetTokenInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/token/{jti}][%d] getTokenInternalServerError ", 500)
}

func (o *GetTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
