// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTokensParams creates a new GetTokensParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTokensParams() *GetTokensParams {
	return &GetTokensParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTokensParamsWithTimeout creates a new GetTokensParams object
// with the ability to set a timeout on a request.
func NewGetTokensParamsWithTimeout(timeout time.Duration) *GetTokensParams {
	return &GetTokensParams{
		timeout: timeout,
	}
}

// NewGetTokensParamsWithContext creates a new GetTokensParams object
// with the ability to set a context for a request.
func NewGetTokensParamsWithContext(ctx context.Context) *GetTokensParams {
	return &GetTokensParams{
		Context: ctx,
	}
}

// NewGetTokensParamsWithHTTPClient creates a new GetTokensParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTokensParamsWithHTTPClient(client *http.Client) *GetTokensParams {
	return &GetTokensParams{
		HTTPClient: client,
	}
}

/*
GetTokensParams contains all the parameters to send to the API endpoint

	for the get tokens operation.

	Typically these are written to a http.Request.
*/
type GetTokensParams struct {

	/* All.

	   Set to true to show revoked / expired tokens
	*/
	All *string

	/* Sub.

	   Subject (user) to retrieve tokens for.
	*/
	Sub *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tokens params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTokensParams) WithDefaults() *GetTokensParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tokens params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTokensParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tokens params
func (o *GetTokensParams) WithTimeout(timeout time.Duration) *GetTokensParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tokens params
func (o *GetTokensParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tokens params
func (o *GetTokensParams) WithContext(ctx context.Context) *GetTokensParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tokens params
func (o *GetTokensParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tokens params
func (o *GetTokensParams) WithHTTPClient(client *http.Client) *GetTokensParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tokens params
func (o *GetTokensParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAll adds the all to the get tokens params
func (o *GetTokensParams) WithAll(all *string) *GetTokensParams {
	o.SetAll(all)
	return o
}

// SetAll adds the all to the get tokens params
func (o *GetTokensParams) SetAll(all *string) {
	o.All = all
}

// WithSub adds the sub to the get tokens params
func (o *GetTokensParams) WithSub(sub *string) *GetTokensParams {
	o.SetSub(sub)
	return o
}

// SetSub adds the sub to the get tokens params
func (o *GetTokensParams) SetSub(sub *string) {
	o.Sub = sub
}

// WriteToRequest writes these params to a swagger request
func (o *GetTokensParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.All != nil {

		// query param all
		var qrAll string

		if o.All != nil {
			qrAll = *o.All
		}
		qAll := qrAll
		if qAll != "" {

			if err := r.SetQueryParam("all", qAll); err != nil {
				return err
			}
		}
	}

	if o.Sub != nil {

		// query param sub
		var qrSub string

		if o.Sub != nil {
			qrSub = *o.Sub
		}
		qSub := qrSub
		if qSub != "" {

			if err := r.SetQueryParam("sub", qSub); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
