// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/tokenservice/models"
)

// GetTokensReader is a Reader for the GetTokens structure.
type GetTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTokensBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetTokensNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTokensInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/tokens] GetTokens", response, response.Code())
	}
}

// NewGetTokensOK creates a GetTokensOK with default headers values
func NewGetTokensOK() *GetTokensOK {
	return &GetTokensOK{}
}

/*
GetTokensOK describes a response with status code 200, with default header values.

Success.
*/
type GetTokensOK struct {
	Payload []*models.TokenDetails
}

// IsSuccess returns true when this get tokens o k response has a 2xx status code
func (o *GetTokensOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tokens o k response has a 3xx status code
func (o *GetTokensOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tokens o k response has a 4xx status code
func (o *GetTokensOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tokens o k response has a 5xx status code
func (o *GetTokensOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tokens o k response a status code equal to that given
func (o *GetTokensOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get tokens o k response
func (o *GetTokensOK) Code() int {
	return 200
}

func (o *GetTokensOK) Error() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensOK  %+v", 200, o.Payload)
}

func (o *GetTokensOK) String() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensOK  %+v", 200, o.Payload)
}

func (o *GetTokensOK) GetPayload() []*models.TokenDetails {
	return o.Payload
}

func (o *GetTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokensBadRequest creates a GetTokensBadRequest with default headers values
func NewGetTokensBadRequest() *GetTokensBadRequest {
	return &GetTokensBadRequest{}
}

/*
GetTokensBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure parameters are supplied correctly.
*/
type GetTokensBadRequest struct {
}

// IsSuccess returns true when this get tokens bad request response has a 2xx status code
func (o *GetTokensBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tokens bad request response has a 3xx status code
func (o *GetTokensBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tokens bad request response has a 4xx status code
func (o *GetTokensBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get tokens bad request response has a 5xx status code
func (o *GetTokensBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get tokens bad request response a status code equal to that given
func (o *GetTokensBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get tokens bad request response
func (o *GetTokensBadRequest) Code() int {
	return 400
}

func (o *GetTokensBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensBadRequest ", 400)
}

func (o *GetTokensBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensBadRequest ", 400)
}

func (o *GetTokensBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTokensNotFound creates a GetTokensNotFound with default headers values
func NewGetTokensNotFound() *GetTokensNotFound {
	return &GetTokensNotFound{}
}

/*
GetTokensNotFound describes a response with status code 404, with default header values.

No tokens found for requested subject.
*/
type GetTokensNotFound struct {
}

// IsSuccess returns true when this get tokens not found response has a 2xx status code
func (o *GetTokensNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tokens not found response has a 3xx status code
func (o *GetTokensNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tokens not found response has a 4xx status code
func (o *GetTokensNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get tokens not found response has a 5xx status code
func (o *GetTokensNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get tokens not found response a status code equal to that given
func (o *GetTokensNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get tokens not found response
func (o *GetTokensNotFound) Code() int {
	return 404
}

func (o *GetTokensNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensNotFound ", 404)
}

func (o *GetTokensNotFound) String() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensNotFound ", 404)
}

func (o *GetTokensNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTokensInternalServerError creates a GetTokensInternalServerError with default headers values
func NewGetTokensInternalServerError() *GetTokensInternalServerError {
	return &GetTokensInternalServerError{}
}

/*
GetTokensInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetTokensInternalServerError struct {
}

// IsSuccess returns true when this get tokens internal server error response has a 2xx status code
func (o *GetTokensInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tokens internal server error response has a 3xx status code
func (o *GetTokensInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tokens internal server error response has a 4xx status code
func (o *GetTokensInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tokens internal server error response has a 5xx status code
func (o *GetTokensInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get tokens internal server error response a status code equal to that given
func (o *GetTokensInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get tokens internal server error response
func (o *GetTokensInternalServerError) Code() int {
	return 500
}

func (o *GetTokensInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensInternalServerError ", 500)
}

func (o *GetTokensInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/tokens][%d] getTokensInternalServerError ", 500)
}

func (o *GetTokensInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
