// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNewTokenParams creates a new NewTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNewTokenParams() *NewTokenParams {
	return &NewTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNewTokenParamsWithTimeout creates a new NewTokenParams object
// with the ability to set a timeout on a request.
func NewNewTokenParamsWithTimeout(timeout time.Duration) *NewTokenParams {
	return &NewTokenParams{
		timeout: timeout,
	}
}

// NewNewTokenParamsWithContext creates a new NewTokenParams object
// with the ability to set a context for a request.
func NewNewTokenParamsWithContext(ctx context.Context) *NewTokenParams {
	return &NewTokenParams{
		Context: ctx,
	}
}

// NewNewTokenParamsWithHTTPClient creates a new NewTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewNewTokenParamsWithHTTPClient(client *http.Client) *NewTokenParams {
	return &NewTokenParams{
		HTTPClient: client,
	}
}

/*
NewTokenParams contains all the parameters to send to the API endpoint

	for the new token operation.

	Typically these are written to a http.Request.
*/
type NewTokenParams struct {

	/* Dur.

	   Lifetime of the token as a golang duration.
	*/
	Dur *string

	/* Lab.

	   Label for the token to allow identification by the user.
	*/
	Lab *string

	/* Sub.

	   Subject (user) for the token to be issued.
	*/
	Sub *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the new token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NewTokenParams) WithDefaults() *NewTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the new token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NewTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the new token params
func (o *NewTokenParams) WithTimeout(timeout time.Duration) *NewTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the new token params
func (o *NewTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the new token params
func (o *NewTokenParams) WithContext(ctx context.Context) *NewTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the new token params
func (o *NewTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the new token params
func (o *NewTokenParams) WithHTTPClient(client *http.Client) *NewTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the new token params
func (o *NewTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDur adds the dur to the new token params
func (o *NewTokenParams) WithDur(dur *string) *NewTokenParams {
	o.SetDur(dur)
	return o
}

// SetDur adds the dur to the new token params
func (o *NewTokenParams) SetDur(dur *string) {
	o.Dur = dur
}

// WithLab adds the lab to the new token params
func (o *NewTokenParams) WithLab(lab *string) *NewTokenParams {
	o.SetLab(lab)
	return o
}

// SetLab adds the lab to the new token params
func (o *NewTokenParams) SetLab(lab *string) {
	o.Lab = lab
}

// WithSub adds the sub to the new token params
func (o *NewTokenParams) WithSub(sub *string) *NewTokenParams {
	o.SetSub(sub)
	return o
}

// SetSub adds the sub to the new token params
func (o *NewTokenParams) SetSub(sub *string) {
	o.Sub = sub
}

// WriteToRequest writes these params to a swagger request
func (o *NewTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Dur != nil {

		// form param dur
		var frDur string
		if o.Dur != nil {
			frDur = *o.Dur
		}
		fDur := frDur
		if fDur != "" {
			if err := r.SetFormParam("dur", fDur); err != nil {
				return err
			}
		}
	}

	if o.Lab != nil {

		// form param lab
		var frLab string
		if o.Lab != nil {
			frLab = *o.Lab
		}
		fLab := frLab
		if fLab != "" {
			if err := r.SetFormParam("lab", fLab); err != nil {
				return err
			}
		}
	}

	if o.Sub != nil {

		// form param sub
		var frSub string
		if o.Sub != nil {
			frSub = *o.Sub
		}
		fSub := frSub
		if fSub != "" {
			if err := r.SetFormParam("sub", fSub); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
