// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewTokenReader is a Reader for the NewToken structure.
type NewTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NewTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNewTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNewTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewNewTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/token/new] NewToken", response, response.Code())
	}
}

// NewNewTokenOK creates a NewTokenOK with default headers values
func NewNewTokenOK() *NewTokenOK {
	return &NewTokenOK{}
}

/*
NewTokenOK describes a response with status code 200, with default header values.

Success.
*/
type NewTokenOK struct {
	Payload string
}

// IsSuccess returns true when this new token o k response has a 2xx status code
func (o *NewTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this new token o k response has a 3xx status code
func (o *NewTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this new token o k response has a 4xx status code
func (o *NewTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this new token o k response has a 5xx status code
func (o *NewTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this new token o k response a status code equal to that given
func (o *NewTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the new token o k response
func (o *NewTokenOK) Code() int {
	return 200
}

func (o *NewTokenOK) Error() string {
	return fmt.Sprintf("[POST /v1/token/new][%d] newTokenOK  %+v", 200, o.Payload)
}

func (o *NewTokenOK) String() string {
	return fmt.Sprintf("[POST /v1/token/new][%d] newTokenOK  %+v", 200, o.Payload)
}

func (o *NewTokenOK) GetPayload() string {
	return o.Payload
}

func (o *NewTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNewTokenBadRequest creates a NewTokenBadRequest with default headers values
func NewNewTokenBadRequest() *NewTokenBadRequest {
	return &NewTokenBadRequest{}
}

/*
NewTokenBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure parameters are supplied correctly.
*/
type NewTokenBadRequest struct {
}

// IsSuccess returns true when this new token bad request response has a 2xx status code
func (o *NewTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this new token bad request response has a 3xx status code
func (o *NewTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this new token bad request response has a 4xx status code
func (o *NewTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this new token bad request response has a 5xx status code
func (o *NewTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this new token bad request response a status code equal to that given
func (o *NewTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the new token bad request response
func (o *NewTokenBadRequest) Code() int {
	return 400
}

func (o *NewTokenBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/token/new][%d] newTokenBadRequest ", 400)
}

func (o *NewTokenBadRequest) String() string {
	return fmt.Sprintf("[POST /v1/token/new][%d] newTokenBadRequest ", 400)
}

func (o *NewTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNewTokenInternalServerError creates a NewTokenInternalServerError with default headers values
func NewNewTokenInternalServerError() *NewTokenInternalServerError {
	return &NewTokenInternalServerError{}
}

/*
NewTokenInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type NewTokenInternalServerError struct {
}

// IsSuccess returns true when this new token internal server error response has a 2xx status code
func (o *NewTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this new token internal server error response has a 3xx status code
func (o *NewTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this new token internal server error response has a 4xx status code
func (o *NewTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this new token internal server error response has a 5xx status code
func (o *NewTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this new token internal server error response a status code equal to that given
func (o *NewTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the new token internal server error response
func (o *NewTokenInternalServerError) Code() int {
	return 500
}

func (o *NewTokenInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/token/new][%d] newTokenInternalServerError ", 500)
}

func (o *NewTokenInternalServerError) String() string {
	return fmt.Sprintf("[POST /v1/token/new][%d] newTokenInternalServerError ", 500)
}

func (o *NewTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
