// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRevokeTokenParams creates a new RevokeTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRevokeTokenParams() *RevokeTokenParams {
	return &RevokeTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRevokeTokenParamsWithTimeout creates a new RevokeTokenParams object
// with the ability to set a timeout on a request.
func NewRevokeTokenParamsWithTimeout(timeout time.Duration) *RevokeTokenParams {
	return &RevokeTokenParams{
		timeout: timeout,
	}
}

// NewRevokeTokenParamsWithContext creates a new RevokeTokenParams object
// with the ability to set a context for a request.
func NewRevokeTokenParamsWithContext(ctx context.Context) *RevokeTokenParams {
	return &RevokeTokenParams{
		Context: ctx,
	}
}

// NewRevokeTokenParamsWithHTTPClient creates a new RevokeTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewRevokeTokenParamsWithHTTPClient(client *http.Client) *RevokeTokenParams {
	return &RevokeTokenParams{
		HTTPClient: client,
	}
}

/*
RevokeTokenParams contains all the parameters to send to the API endpoint

	for the revoke token operation.

	Typically these are written to a http.Request.
*/
type RevokeTokenParams struct {

	/* Jti.

	   Token BSON ID of token to revoke. May be "all" when request being performed as admin and "sub" is specified.
	*/
	Jti string

	/* Sub.

	   Subject of tokens to revoke. Must be defined if jti is "all"
	*/
	Sub *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the revoke token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RevokeTokenParams) WithDefaults() *RevokeTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the revoke token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RevokeTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the revoke token params
func (o *RevokeTokenParams) WithTimeout(timeout time.Duration) *RevokeTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the revoke token params
func (o *RevokeTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the revoke token params
func (o *RevokeTokenParams) WithContext(ctx context.Context) *RevokeTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the revoke token params
func (o *RevokeTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the revoke token params
func (o *RevokeTokenParams) WithHTTPClient(client *http.Client) *RevokeTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the revoke token params
func (o *RevokeTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJti adds the jti to the revoke token params
func (o *RevokeTokenParams) WithJti(jti string) *RevokeTokenParams {
	o.SetJti(jti)
	return o
}

// SetJti adds the jti to the revoke token params
func (o *RevokeTokenParams) SetJti(jti string) {
	o.Jti = jti
}

// WithSub adds the sub to the revoke token params
func (o *RevokeTokenParams) WithSub(sub *string) *RevokeTokenParams {
	o.SetSub(sub)
	return o
}

// SetSub adds the sub to the revoke token params
func (o *RevokeTokenParams) SetSub(sub *string) {
	o.Sub = sub
}

// WriteToRequest writes these params to a swagger request
func (o *RevokeTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param jti
	if err := r.SetPathParam("jti", o.Jti); err != nil {
		return err
	}

	if o.Sub != nil {

		// query param sub
		var qrSub string

		if o.Sub != nil {
			qrSub = *o.Sub
		}
		qSub := qrSub
		if qSub != "" {

			if err := r.SetQueryParam("sub", qSub); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
