// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RevokeTokenReader is a Reader for the RevokeToken structure.
type RevokeTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevokeTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRevokeTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRevokeTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokeTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/token/{jti}] RevokeToken", response, response.Code())
	}
}

// NewRevokeTokenOK creates a RevokeTokenOK with default headers values
func NewRevokeTokenOK() *RevokeTokenOK {
	return &RevokeTokenOK{}
}

/*
RevokeTokenOK describes a response with status code 200, with default header values.

Success.
*/
type RevokeTokenOK struct {
}

// IsSuccess returns true when this revoke token o k response has a 2xx status code
func (o *RevokeTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this revoke token o k response has a 3xx status code
func (o *RevokeTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke token o k response has a 4xx status code
func (o *RevokeTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke token o k response has a 5xx status code
func (o *RevokeTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke token o k response a status code equal to that given
func (o *RevokeTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the revoke token o k response
func (o *RevokeTokenOK) Code() int {
	return 200
}

func (o *RevokeTokenOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenOK ", 200)
}

func (o *RevokeTokenOK) String() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenOK ", 200)
}

func (o *RevokeTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeTokenBadRequest creates a RevokeTokenBadRequest with default headers values
func NewRevokeTokenBadRequest() *RevokeTokenBadRequest {
	return &RevokeTokenBadRequest{}
}

/*
RevokeTokenBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure parameters are supplied correctly.
*/
type RevokeTokenBadRequest struct {
}

// IsSuccess returns true when this revoke token bad request response has a 2xx status code
func (o *RevokeTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke token bad request response has a 3xx status code
func (o *RevokeTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke token bad request response has a 4xx status code
func (o *RevokeTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke token bad request response has a 5xx status code
func (o *RevokeTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke token bad request response a status code equal to that given
func (o *RevokeTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the revoke token bad request response
func (o *RevokeTokenBadRequest) Code() int {
	return 400
}

func (o *RevokeTokenBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenBadRequest ", 400)
}

func (o *RevokeTokenBadRequest) String() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenBadRequest ", 400)
}

func (o *RevokeTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeTokenNotFound creates a RevokeTokenNotFound with default headers values
func NewRevokeTokenNotFound() *RevokeTokenNotFound {
	return &RevokeTokenNotFound{}
}

/*
RevokeTokenNotFound describes a response with status code 404, with default header values.

Requested token was not found.
*/
type RevokeTokenNotFound struct {
}

// IsSuccess returns true when this revoke token not found response has a 2xx status code
func (o *RevokeTokenNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke token not found response has a 3xx status code
func (o *RevokeTokenNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke token not found response has a 4xx status code
func (o *RevokeTokenNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke token not found response has a 5xx status code
func (o *RevokeTokenNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke token not found response a status code equal to that given
func (o *RevokeTokenNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the revoke token not found response
func (o *RevokeTokenNotFound) Code() int {
	return 404
}

func (o *RevokeTokenNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenNotFound ", 404)
}

func (o *RevokeTokenNotFound) String() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenNotFound ", 404)
}

func (o *RevokeTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeTokenInternalServerError creates a RevokeTokenInternalServerError with default headers values
func NewRevokeTokenInternalServerError() *RevokeTokenInternalServerError {
	return &RevokeTokenInternalServerError{}
}

/*
RevokeTokenInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type RevokeTokenInternalServerError struct {
}

// IsSuccess returns true when this revoke token internal server error response has a 2xx status code
func (o *RevokeTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke token internal server error response has a 3xx status code
func (o *RevokeTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke token internal server error response has a 4xx status code
func (o *RevokeTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke token internal server error response has a 5xx status code
func (o *RevokeTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this revoke token internal server error response a status code equal to that given
func (o *RevokeTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the revoke token internal server error response
func (o *RevokeTokenInternalServerError) Code() int {
	return 500
}

func (o *RevokeTokenInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenInternalServerError ", 500)
}

func (o *RevokeTokenInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /v1/token/{jti}][%d] revokeTokenInternalServerError ", 500)
}

func (o *RevokeTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
