// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TokenStatusReader is a Reader for the TokenStatus structure.
type TokenStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TokenStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTokenStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewTokenStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTokenStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/token-status] TokenStatus", response, response.Code())
	}
}

// NewTokenStatusOK creates a TokenStatusOK with default headers values
func NewTokenStatusOK() *TokenStatusOK {
	return &TokenStatusOK{}
}

/*
TokenStatusOK describes a response with status code 200, with default header values.

Token is valid.
*/
type TokenStatusOK struct {
}

// IsSuccess returns true when this token status o k response has a 2xx status code
func (o *TokenStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this token status o k response has a 3xx status code
func (o *TokenStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this token status o k response has a 4xx status code
func (o *TokenStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this token status o k response has a 5xx status code
func (o *TokenStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this token status o k response a status code equal to that given
func (o *TokenStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the token status o k response
func (o *TokenStatusOK) Code() int {
	return 200
}

func (o *TokenStatusOK) Error() string {
	return fmt.Sprintf("[GET /v1/token-status][%d] tokenStatusOK ", 200)
}

func (o *TokenStatusOK) String() string {
	return fmt.Sprintf("[GET /v1/token-status][%d] tokenStatusOK ", 200)
}

func (o *TokenStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTokenStatusNotFound creates a TokenStatusNotFound with default headers values
func NewTokenStatusNotFound() *TokenStatusNotFound {
	return &TokenStatusNotFound{}
}

/*
TokenStatusNotFound describes a response with status code 404, with default header values.

Token is not found or was revoked.
*/
type TokenStatusNotFound struct {
}

// IsSuccess returns true when this token status not found response has a 2xx status code
func (o *TokenStatusNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this token status not found response has a 3xx status code
func (o *TokenStatusNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this token status not found response has a 4xx status code
func (o *TokenStatusNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this token status not found response has a 5xx status code
func (o *TokenStatusNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this token status not found response a status code equal to that given
func (o *TokenStatusNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the token status not found response
func (o *TokenStatusNotFound) Code() int {
	return 404
}

func (o *TokenStatusNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/token-status][%d] tokenStatusNotFound ", 404)
}

func (o *TokenStatusNotFound) String() string {
	return fmt.Sprintf("[GET /v1/token-status][%d] tokenStatusNotFound ", 404)
}

func (o *TokenStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTokenStatusInternalServerError creates a TokenStatusInternalServerError with default headers values
func NewTokenStatusInternalServerError() *TokenStatusInternalServerError {
	return &TokenStatusInternalServerError{}
}

/*
TokenStatusInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type TokenStatusInternalServerError struct {
}

// IsSuccess returns true when this token status internal server error response has a 2xx status code
func (o *TokenStatusInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this token status internal server error response has a 3xx status code
func (o *TokenStatusInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this token status internal server error response has a 4xx status code
func (o *TokenStatusInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this token status internal server error response has a 5xx status code
func (o *TokenStatusInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this token status internal server error response a status code equal to that given
func (o *TokenStatusInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the token status internal server error response
func (o *TokenStatusInternalServerError) Code() int {
	return 500
}

func (o *TokenStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/token-status][%d] tokenStatusInternalServerError ", 500)
}

func (o *TokenStatusInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/token-status][%d] tokenStatusInternalServerError ", 500)
}

func (o *TokenStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
