// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTokenStatusParams creates a new TokenStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTokenStatusParams() *TokenStatusParams {
	return &TokenStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTokenStatusParamsWithTimeout creates a new TokenStatusParams object
// with the ability to set a timeout on a request.
func NewTokenStatusParamsWithTimeout(timeout time.Duration) *TokenStatusParams {
	return &TokenStatusParams{
		timeout: timeout,
	}
}

// NewTokenStatusParamsWithContext creates a new TokenStatusParams object
// with the ability to set a context for a request.
func NewTokenStatusParamsWithContext(ctx context.Context) *TokenStatusParams {
	return &TokenStatusParams{
		Context: ctx,
	}
}

// NewTokenStatusParamsWithHTTPClient creates a new TokenStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewTokenStatusParamsWithHTTPClient(client *http.Client) *TokenStatusParams {
	return &TokenStatusParams{
		HTTPClient: client,
	}
}

/*
TokenStatusParams contains all the parameters to send to the API endpoint

	for the token status operation.

	Typically these are written to a http.Request.
*/
type TokenStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the token status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TokenStatusParams) WithDefaults() *TokenStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the token status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TokenStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the token status params
func (o *TokenStatusParams) WithTimeout(timeout time.Duration) *TokenStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the token status params
func (o *TokenStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the token status params
func (o *TokenStatusParams) WithContext(ctx context.Context) *TokenStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the token status params
func (o *TokenStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the token status params
func (o *TokenStatusParams) WithHTTPClient(client *http.Client) *TokenStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the token status params
func (o *TokenStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *TokenStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
