BootStrap: docker
From: busybox:latest   # This is a comment

%runscript
    echo "This is what happens when you run the container..."

%post
    echo "Hello from inside the container"
    echo "Install additional software here"

%test
    echo "Hello from the test script"

