// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentInfo Information about an Agent.
//
// swagger:model AgentInfo
type AgentInfo struct {

	// Date/time when Agent was added.
	// Example: 2018-10-28T16:45:03.6037837Z
	AddedAt string `json:"addedAt,omitempty"`

	// Hostname of Agent.
	// Example: 8a62f2d3b523
	Address string `json:"address,omitempty"`

	// UUID of the Agent.
	// Example: 0a6bccb3-094f-4c65-a8cd-2903e4672968
	ID string `json:"id,omitempty"`

	// Name of the AMQP queue the Agent accepts messages on.
	// Example: 0a6bccb3-094f-4c65-a8cd-2903e4672968
	Queue string `json:"queue,omitempty"`

	// BSON ID of current task.
	// Example: 5af05d5e9293620001b41d2c
	TaskID string `json:"taskID,omitempty"`

	// Date/time current task was assigned.
	// Example: 2018-10-28T16:51:02.8492307Z
	TaskedAt string `json:"taskedAt,omitempty"`
}

// Validate validates this agent info
func (m *AgentInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent info based on context it is used
func (m *AgentInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentInfo) UnmarshalBinary(b []byte) error {
	var res AgentInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
