// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// ActivateUserReader is a Reader for the ActivateUser structure.
type ActivateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActivateUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewActivateUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewActivateUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewActivateUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewActivateUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewActivateUserOK creates a ActivateUserOK with default headers values
func NewActivateUserOK() *ActivateUserOK {
	return &ActivateUserOK{}
}

/*
	ActivateUserOK describes a response with status code 200, with default header values.

Success
*/
type ActivateUserOK struct {
	Payload *models.UserResponse
}

func (o *ActivateUserOK) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/activate][%d] activateUserOK  %+v", 200, o.Payload)
}
func (o *ActivateUserOK) GetPayload() *models.UserResponse {
	return o.Payload
}

func (o *ActivateUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivateUserBadRequest creates a ActivateUserBadRequest with default headers values
func NewActivateUserBadRequest() *ActivateUserBadRequest {
	return &ActivateUserBadRequest{}
}

/*
	ActivateUserBadRequest describes a response with status code 400, with default header values.

Bad request - user id not valid
*/
type ActivateUserBadRequest struct {
	Payload *models.Json400error
}

func (o *ActivateUserBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/activate][%d] activateUserBadRequest  %+v", 400, o.Payload)
}
func (o *ActivateUserBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *ActivateUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivateUserUnauthorized creates a ActivateUserUnauthorized with default headers values
func NewActivateUserUnauthorized() *ActivateUserUnauthorized {
	return &ActivateUserUnauthorized{}
}

/*
	ActivateUserUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type ActivateUserUnauthorized struct {
	Payload *models.Json401error
}

func (o *ActivateUserUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/activate][%d] activateUserUnauthorized  %+v", 401, o.Payload)
}
func (o *ActivateUserUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *ActivateUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivateUserNotFound creates a ActivateUserNotFound with default headers values
func NewActivateUserNotFound() *ActivateUserNotFound {
	return &ActivateUserNotFound{}
}

/*
	ActivateUserNotFound describes a response with status code 404, with default header values.

Bad request - user id not found
*/
type ActivateUserNotFound struct {
	Payload *models.Json404error
}

func (o *ActivateUserNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/activate][%d] activateUserNotFound  %+v", 404, o.Payload)
}
func (o *ActivateUserNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *ActivateUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivateUserInternalServerError creates a ActivateUserInternalServerError with default headers values
func NewActivateUserInternalServerError() *ActivateUserInternalServerError {
	return &ActivateUserInternalServerError{}
}

/*
	ActivateUserInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ActivateUserInternalServerError struct {
	Payload *models.Json500error
}

func (o *ActivateUserInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/activate][%d] activateUserInternalServerError  %+v", 500, o.Payload)
}
func (o *ActivateUserInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *ActivateUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
