// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// DeactivateUserReader is a Reader for the DeactivateUser structure.
type DeactivateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeactivateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeactivateUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeactivateUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeactivateUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeactivateUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeactivateUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeactivateUserOK creates a DeactivateUserOK with default headers values
func NewDeactivateUserOK() *DeactivateUserOK {
	return &DeactivateUserOK{}
}

/*
	DeactivateUserOK describes a response with status code 200, with default header values.

Success
*/
type DeactivateUserOK struct {
	Payload *models.UserResponse
}

func (o *DeactivateUserOK) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/deactivate][%d] deactivateUserOK  %+v", 200, o.Payload)
}
func (o *DeactivateUserOK) GetPayload() *models.UserResponse {
	return o.Payload
}

func (o *DeactivateUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeactivateUserBadRequest creates a DeactivateUserBadRequest with default headers values
func NewDeactivateUserBadRequest() *DeactivateUserBadRequest {
	return &DeactivateUserBadRequest{}
}

/*
	DeactivateUserBadRequest describes a response with status code 400, with default header values.

Bad request - user id not valid
*/
type DeactivateUserBadRequest struct {
	Payload *models.Json400error
}

func (o *DeactivateUserBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/deactivate][%d] deactivateUserBadRequest  %+v", 400, o.Payload)
}
func (o *DeactivateUserBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *DeactivateUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeactivateUserUnauthorized creates a DeactivateUserUnauthorized with default headers values
func NewDeactivateUserUnauthorized() *DeactivateUserUnauthorized {
	return &DeactivateUserUnauthorized{}
}

/*
	DeactivateUserUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type DeactivateUserUnauthorized struct {
	Payload *models.Json401error
}

func (o *DeactivateUserUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/deactivate][%d] deactivateUserUnauthorized  %+v", 401, o.Payload)
}
func (o *DeactivateUserUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *DeactivateUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeactivateUserNotFound creates a DeactivateUserNotFound with default headers values
func NewDeactivateUserNotFound() *DeactivateUserNotFound {
	return &DeactivateUserNotFound{}
}

/*
	DeactivateUserNotFound describes a response with status code 404, with default header values.

Bad request - user id not found
*/
type DeactivateUserNotFound struct {
	Payload *models.Json404error
}

func (o *DeactivateUserNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/deactivate][%d] deactivateUserNotFound  %+v", 404, o.Payload)
}
func (o *DeactivateUserNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *DeactivateUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeactivateUserInternalServerError creates a DeactivateUserInternalServerError with default headers values
func NewDeactivateUserInternalServerError() *DeactivateUserInternalServerError {
	return &DeactivateUserInternalServerError{}
}

/*
	DeactivateUserInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeactivateUserInternalServerError struct {
	Payload *models.Json500error
}

func (o *DeactivateUserInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/deactivate][%d] deactivateUserInternalServerError  %+v", 500, o.Payload)
}
func (o *DeactivateUserInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *DeactivateUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
