// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// NewUpdateUserQuotaParams creates a new UpdateUserQuotaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateUserQuotaParams() *UpdateUserQuotaParams {
	return &UpdateUserQuotaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateUserQuotaParamsWithTimeout creates a new UpdateUserQuotaParams object
// with the ability to set a timeout on a request.
func NewUpdateUserQuotaParamsWithTimeout(timeout time.Duration) *UpdateUserQuotaParams {
	return &UpdateUserQuotaParams{
		timeout: timeout,
	}
}

// NewUpdateUserQuotaParamsWithContext creates a new UpdateUserQuotaParams object
// with the ability to set a context for a request.
func NewUpdateUserQuotaParamsWithContext(ctx context.Context) *UpdateUserQuotaParams {
	return &UpdateUserQuotaParams{
		Context: ctx,
	}
}

// NewUpdateUserQuotaParamsWithHTTPClient creates a new UpdateUserQuotaParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateUserQuotaParamsWithHTTPClient(client *http.Client) *UpdateUserQuotaParams {
	return &UpdateUserQuotaParams{
		HTTPClient: client,
	}
}

/*
UpdateUserQuotaParams contains all the parameters to send to the API endpoint

	for the update user quota operation.

	Typically these are written to a http.Request.
*/
type UpdateUserQuotaParams struct {

	// UpdateUserQuotaRequestBody.
	UpdateUserQuotaRequestBody *models.UserQuota

	/* UserID.

	   BSON ID of user to update
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update user quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserQuotaParams) WithDefaults() *UpdateUserQuotaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update user quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserQuotaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update user quota params
func (o *UpdateUserQuotaParams) WithTimeout(timeout time.Duration) *UpdateUserQuotaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update user quota params
func (o *UpdateUserQuotaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update user quota params
func (o *UpdateUserQuotaParams) WithContext(ctx context.Context) *UpdateUserQuotaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update user quota params
func (o *UpdateUserQuotaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update user quota params
func (o *UpdateUserQuotaParams) WithHTTPClient(client *http.Client) *UpdateUserQuotaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update user quota params
func (o *UpdateUserQuotaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateUserQuotaRequestBody adds the updateUserQuotaRequestBody to the update user quota params
func (o *UpdateUserQuotaParams) WithUpdateUserQuotaRequestBody(updateUserQuotaRequestBody *models.UserQuota) *UpdateUserQuotaParams {
	o.SetUpdateUserQuotaRequestBody(updateUserQuotaRequestBody)
	return o
}

// SetUpdateUserQuotaRequestBody adds the updateUserQuotaRequestBody to the update user quota params
func (o *UpdateUserQuotaParams) SetUpdateUserQuotaRequestBody(updateUserQuotaRequestBody *models.UserQuota) {
	o.UpdateUserQuotaRequestBody = updateUserQuotaRequestBody
}

// WithUserID adds the userID to the update user quota params
func (o *UpdateUserQuotaParams) WithUserID(userID string) *UpdateUserQuotaParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the update user quota params
func (o *UpdateUserQuotaParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateUserQuotaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.UpdateUserQuotaRequestBody != nil {
		if err := r.SetBodyParam(o.UpdateUserQuotaRequestBody); err != nil {
			return err
		}
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
