// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserRemoveGroupParams creates a new UserRemoveGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserRemoveGroupParams() *UserRemoveGroupParams {
	return &UserRemoveGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserRemoveGroupParamsWithTimeout creates a new UserRemoveGroupParams object
// with the ability to set a timeout on a request.
func NewUserRemoveGroupParamsWithTimeout(timeout time.Duration) *UserRemoveGroupParams {
	return &UserRemoveGroupParams{
		timeout: timeout,
	}
}

// NewUserRemoveGroupParamsWithContext creates a new UserRemoveGroupParams object
// with the ability to set a context for a request.
func NewUserRemoveGroupParamsWithContext(ctx context.Context) *UserRemoveGroupParams {
	return &UserRemoveGroupParams{
		Context: ctx,
	}
}

// NewUserRemoveGroupParamsWithHTTPClient creates a new UserRemoveGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserRemoveGroupParamsWithHTTPClient(client *http.Client) *UserRemoveGroupParams {
	return &UserRemoveGroupParams{
		HTTPClient: client,
	}
}

/* UserRemoveGroupParams contains all the parameters to send to the API endpoint
   for the user remove group operation.

   Typically these are written to a http.Request.
*/
type UserRemoveGroupParams struct {

	/* Group.

	   Name of group
	*/
	Group string

	/* UserID.

	   BSON ID of user to remove from group
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user remove group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserRemoveGroupParams) WithDefaults() *UserRemoveGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user remove group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserRemoveGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user remove group params
func (o *UserRemoveGroupParams) WithTimeout(timeout time.Duration) *UserRemoveGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user remove group params
func (o *UserRemoveGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user remove group params
func (o *UserRemoveGroupParams) WithContext(ctx context.Context) *UserRemoveGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user remove group params
func (o *UserRemoveGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user remove group params
func (o *UserRemoveGroupParams) WithHTTPClient(client *http.Client) *UserRemoveGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user remove group params
func (o *UserRemoveGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the user remove group params
func (o *UserRemoveGroupParams) WithGroup(group string) *UserRemoveGroupParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the user remove group params
func (o *UserRemoveGroupParams) SetGroup(group string) {
	o.Group = group
}

// WithUserID adds the userID to the user remove group params
func (o *UserRemoveGroupParams) WithUserID(userID string) *UserRemoveGroupParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user remove group params
func (o *UserRemoveGroupParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserRemoveGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group
	if err := r.SetPathParam("group", o.Group); err != nil {
		return err
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
