// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// UserRemoveGroupReader is a Reader for the UserRemoveGroup structure.
type UserRemoveGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserRemoveGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserRemoveGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUserRemoveGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUserRemoveGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUserRemoveGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUserRemoveGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserRemoveGroupOK creates a UserRemoveGroupOK with default headers values
func NewUserRemoveGroupOK() *UserRemoveGroupOK {
	return &UserRemoveGroupOK{}
}

/*
	UserRemoveGroupOK describes a response with status code 200, with default header values.

Success
*/
type UserRemoveGroupOK struct {
	Payload *models.UserResponse
}

func (o *UserRemoveGroupOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/users/{userID}/group/{group}][%d] userRemoveGroupOK  %+v", 200, o.Payload)
}
func (o *UserRemoveGroupOK) GetPayload() *models.UserResponse {
	return o.Payload
}

func (o *UserRemoveGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserRemoveGroupBadRequest creates a UserRemoveGroupBadRequest with default headers values
func NewUserRemoveGroupBadRequest() *UserRemoveGroupBadRequest {
	return &UserRemoveGroupBadRequest{}
}

/*
	UserRemoveGroupBadRequest describes a response with status code 400, with default header values.

Bad request - user id or group not valid
*/
type UserRemoveGroupBadRequest struct {
	Payload *models.Json400error
}

func (o *UserRemoveGroupBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/users/{userID}/group/{group}][%d] userRemoveGroupBadRequest  %+v", 400, o.Payload)
}
func (o *UserRemoveGroupBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *UserRemoveGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserRemoveGroupUnauthorized creates a UserRemoveGroupUnauthorized with default headers values
func NewUserRemoveGroupUnauthorized() *UserRemoveGroupUnauthorized {
	return &UserRemoveGroupUnauthorized{}
}

/*
	UserRemoveGroupUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type UserRemoveGroupUnauthorized struct {
	Payload *models.Json401error
}

func (o *UserRemoveGroupUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/users/{userID}/group/{group}][%d] userRemoveGroupUnauthorized  %+v", 401, o.Payload)
}
func (o *UserRemoveGroupUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *UserRemoveGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserRemoveGroupNotFound creates a UserRemoveGroupNotFound with default headers values
func NewUserRemoveGroupNotFound() *UserRemoveGroupNotFound {
	return &UserRemoveGroupNotFound{}
}

/*
	UserRemoveGroupNotFound describes a response with status code 404, with default header values.

Bad request - user id not found
*/
type UserRemoveGroupNotFound struct {
	Payload *models.Json404error
}

func (o *UserRemoveGroupNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/users/{userID}/group/{group}][%d] userRemoveGroupNotFound  %+v", 404, o.Payload)
}
func (o *UserRemoveGroupNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *UserRemoveGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserRemoveGroupInternalServerError creates a UserRemoveGroupInternalServerError with default headers values
func NewUserRemoveGroupInternalServerError() *UserRemoveGroupInternalServerError {
	return &UserRemoveGroupInternalServerError{}
}

/*
	UserRemoveGroupInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type UserRemoveGroupInternalServerError struct {
	Payload *models.Json500error
}

func (o *UserRemoveGroupInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/users/{userID}/group/{group}][%d] userRemoveGroupInternalServerError  %+v", 500, o.Payload)
}
func (o *UserRemoveGroupInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *UserRemoveGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
