// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserAddRoleParams creates a new UserAddRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserAddRoleParams() *UserAddRoleParams {
	return &UserAddRoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserAddRoleParamsWithTimeout creates a new UserAddRoleParams object
// with the ability to set a timeout on a request.
func NewUserAddRoleParamsWithTimeout(timeout time.Duration) *UserAddRoleParams {
	return &UserAddRoleParams{
		timeout: timeout,
	}
}

// NewUserAddRoleParamsWithContext creates a new UserAddRoleParams object
// with the ability to set a context for a request.
func NewUserAddRoleParamsWithContext(ctx context.Context) *UserAddRoleParams {
	return &UserAddRoleParams{
		Context: ctx,
	}
}

// NewUserAddRoleParamsWithHTTPClient creates a new UserAddRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserAddRoleParamsWithHTTPClient(client *http.Client) *UserAddRoleParams {
	return &UserAddRoleParams{
		HTTPClient: client,
	}
}

/* UserAddRoleParams contains all the parameters to send to the API endpoint
   for the user add role operation.

   Typically these are written to a http.Request.
*/
type UserAddRoleParams struct {

	/* Role.

	   Name of role
	*/
	Role string

	/* UserID.

	   BSON ID of user to add to role
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user add role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserAddRoleParams) WithDefaults() *UserAddRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user add role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserAddRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user add role params
func (o *UserAddRoleParams) WithTimeout(timeout time.Duration) *UserAddRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user add role params
func (o *UserAddRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user add role params
func (o *UserAddRoleParams) WithContext(ctx context.Context) *UserAddRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user add role params
func (o *UserAddRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user add role params
func (o *UserAddRoleParams) WithHTTPClient(client *http.Client) *UserAddRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user add role params
func (o *UserAddRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the user add role params
func (o *UserAddRoleParams) WithRole(role string) *UserAddRoleParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the user add role params
func (o *UserAddRoleParams) SetRole(role string) {
	o.Role = role
}

// WithUserID adds the userID to the user add role params
func (o *UserAddRoleParams) WithUserID(userID string) *UserAddRoleParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user add role params
func (o *UserAddRoleParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserAddRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
