// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// UserAddRoleReader is a Reader for the UserAddRole structure.
type UserAddRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserAddRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserAddRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUserAddRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUserAddRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUserAddRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUserAddRoleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserAddRoleOK creates a UserAddRoleOK with default headers values
func NewUserAddRoleOK() *UserAddRoleOK {
	return &UserAddRoleOK{}
}

/*
	UserAddRoleOK describes a response with status code 200, with default header values.

Success
*/
type UserAddRoleOK struct {
	Payload *models.UserResponse
}

func (o *UserAddRoleOK) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/role/{role}][%d] userAddRoleOK  %+v", 200, o.Payload)
}
func (o *UserAddRoleOK) GetPayload() *models.UserResponse {
	return o.Payload
}

func (o *UserAddRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserAddRoleBadRequest creates a UserAddRoleBadRequest with default headers values
func NewUserAddRoleBadRequest() *UserAddRoleBadRequest {
	return &UserAddRoleBadRequest{}
}

/*
	UserAddRoleBadRequest describes a response with status code 400, with default header values.

Bad request - user id or role not valid
*/
type UserAddRoleBadRequest struct {
	Payload *models.Json400error
}

func (o *UserAddRoleBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/role/{role}][%d] userAddRoleBadRequest  %+v", 400, o.Payload)
}
func (o *UserAddRoleBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *UserAddRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserAddRoleUnauthorized creates a UserAddRoleUnauthorized with default headers values
func NewUserAddRoleUnauthorized() *UserAddRoleUnauthorized {
	return &UserAddRoleUnauthorized{}
}

/*
	UserAddRoleUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type UserAddRoleUnauthorized struct {
	Payload *models.Json401error
}

func (o *UserAddRoleUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/role/{role}][%d] userAddRoleUnauthorized  %+v", 401, o.Payload)
}
func (o *UserAddRoleUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *UserAddRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserAddRoleNotFound creates a UserAddRoleNotFound with default headers values
func NewUserAddRoleNotFound() *UserAddRoleNotFound {
	return &UserAddRoleNotFound{}
}

/*
	UserAddRoleNotFound describes a response with status code 404, with default header values.

Bad request - user id not found
*/
type UserAddRoleNotFound struct {
	Payload *models.Json404error
}

func (o *UserAddRoleNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/role/{role}][%d] userAddRoleNotFound  %+v", 404, o.Payload)
}
func (o *UserAddRoleNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *UserAddRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserAddRoleInternalServerError creates a UserAddRoleInternalServerError with default headers values
func NewUserAddRoleInternalServerError() *UserAddRoleInternalServerError {
	return &UserAddRoleInternalServerError{}
}

/*
	UserAddRoleInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type UserAddRoleInternalServerError struct {
	Payload *models.Json500error
}

func (o *UserAddRoleInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/admin/users/{userID}/role/{role}][%d] userAddRoleInternalServerError  %+v", 500, o.Payload)
}
func (o *UserAddRoleInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *UserAddRoleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
