// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserAddGroupParams creates a new UserAddGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserAddGroupParams() *UserAddGroupParams {
	return &UserAddGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserAddGroupParamsWithTimeout creates a new UserAddGroupParams object
// with the ability to set a timeout on a request.
func NewUserAddGroupParamsWithTimeout(timeout time.Duration) *UserAddGroupParams {
	return &UserAddGroupParams{
		timeout: timeout,
	}
}

// NewUserAddGroupParamsWithContext creates a new UserAddGroupParams object
// with the ability to set a context for a request.
func NewUserAddGroupParamsWithContext(ctx context.Context) *UserAddGroupParams {
	return &UserAddGroupParams{
		Context: ctx,
	}
}

// NewUserAddGroupParamsWithHTTPClient creates a new UserAddGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserAddGroupParamsWithHTTPClient(client *http.Client) *UserAddGroupParams {
	return &UserAddGroupParams{
		HTTPClient: client,
	}
}

/* UserAddGroupParams contains all the parameters to send to the API endpoint
   for the user add group operation.

   Typically these are written to a http.Request.
*/
type UserAddGroupParams struct {

	/* Group.

	   Name of group
	*/
	Group string

	/* UserID.

	   BSON ID of user to add to group
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user add group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserAddGroupParams) WithDefaults() *UserAddGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user add group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserAddGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user add group params
func (o *UserAddGroupParams) WithTimeout(timeout time.Duration) *UserAddGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user add group params
func (o *UserAddGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user add group params
func (o *UserAddGroupParams) WithContext(ctx context.Context) *UserAddGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user add group params
func (o *UserAddGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user add group params
func (o *UserAddGroupParams) WithHTTPClient(client *http.Client) *UserAddGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user add group params
func (o *UserAddGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the user add group params
func (o *UserAddGroupParams) WithGroup(group string) *UserAddGroupParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the user add group params
func (o *UserAddGroupParams) SetGroup(group string) {
	o.Group = group
}

// WithUserID adds the userID to the user add group params
func (o *UserAddGroupParams) WithUserID(userID string) *UserAddGroupParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user add group params
func (o *UserAddGroupParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserAddGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group
	if err := r.SetPathParam("group", o.Group); err != nil {
		return err
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
