// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserStatsParams creates a new UserStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserStatsParams() *UserStatsParams {
	return &UserStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserStatsParamsWithTimeout creates a new UserStatsParams object
// with the ability to set a timeout on a request.
func NewUserStatsParamsWithTimeout(timeout time.Duration) *UserStatsParams {
	return &UserStatsParams{
		timeout: timeout,
	}
}

// NewUserStatsParamsWithContext creates a new UserStatsParams object
// with the ability to set a context for a request.
func NewUserStatsParamsWithContext(ctx context.Context) *UserStatsParams {
	return &UserStatsParams{
		Context: ctx,
	}
}

// NewUserStatsParamsWithHTTPClient creates a new UserStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserStatsParamsWithHTTPClient(client *http.Client) *UserStatsParams {
	return &UserStatsParams{
		HTTPClient: client,
	}
}

/* UserStatsParams contains all the parameters to send to the API endpoint
   for the user stats operation.

   Typically these are written to a http.Request.
*/
type UserStatsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserStatsParams) WithDefaults() *UserStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user stats params
func (o *UserStatsParams) WithTimeout(timeout time.Duration) *UserStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user stats params
func (o *UserStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user stats params
func (o *UserStatsParams) WithContext(ctx context.Context) *UserStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user stats params
func (o *UserStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user stats params
func (o *UserStatsParams) WithHTTPClient(client *http.Client) *UserStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user stats params
func (o *UserStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UserStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
