// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Json500error json500error
//
// swagger:model json500error
type Json500error struct {

	// code
	// Example: 500
	Code int64 `json:"code,omitempty"`

	// message
	// Example: See server logs for details
	Message string `json:"message,omitempty"`

	// status
	// Example: Internal Server Error
	Status string `json:"status,omitempty"`
}

// Validate validates this json500error
func (m *Json500error) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this json500error based on context it is used
func (m *Json500error) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Json500error) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Json500error) UnmarshalBinary(b []byte) error {
	var res Json500error
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
