// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Json404error json404error
//
// swagger:model json404error
type Json404error struct {

	// code
	// Example: 404
	Code int64 `json:"code,omitempty"`

	// message
	// Example: \u003cmodel\u003e \u003cid\u003e not found.
	Message string `json:"message,omitempty"`

	// status
	// Example: Not Found
	Status string `json:"status,omitempty"`
}

// Validate validates this json404error
func (m *Json404error) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this json404error based on context it is used
func (m *Json404error) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Json404error) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Json404error) UnmarshalBinary(b []byte) error {
	var res Json404error
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
