// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Organization An organization which groups users, groups, roles
//
// swagger:model organization
type Organization struct {

	// Date/Time organization was created, RFC3339 format.
	// Example: 2019-02-26T03:32:33.587Z
	CreatedAt string `json:"createdAt,omitempty"`

	// Description of the purpose of the organization
	// Example: Primary Organization
	Description string `json:"description,omitempty"`

	// BSON identifier for the organization.
	// Example: 507f1f77bcf86cd799439ddd
	ID string `json:"id,omitempty"`

	// Canonical name for the organization
	// Example: primary
	Name string `json:"name,omitempty"`
}

// Validate validates this organization
func (m *Organization) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this organization based on context it is used
func (m *Organization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Organization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Organization) UnmarshalBinary(b []byte) error {
	var res Organization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
