// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Role A role, conveying permissions to a user or a group
//
// swagger:model role
type Role struct {

	// Date/Time role was created, RFC3339 format.
	// Example: 2019-02-26T03:32:33.587Z
	CreatedAt string `json:"createdAt,omitempty"`

	// Description of the purpose of the role
	// Example: Authentication system administrative permissions
	Description string `json:"description,omitempty"`

	// BSON identifier for the role.
	// Example: 507f1f77bcf86cd799439ccc
	ID string `json:"id,omitempty"`

	// Canonical name for the role - used as the identifying field
	// Example: auth-admin
	Name string `json:"name,omitempty"`

	// BSON identifier for the organization this role belongs to. Currently a fixed primary organization
	// Example: 507f1f77bcf86cd799439ddd
	OrganizationID string `json:"organizationID,omitempty"`
}

// Validate validates this role
func (m *Role) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this role based on context it is used
func (m *Role) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Role) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Role) UnmarshalBinary(b []byte) error {
	var res Role
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
