// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserQuota User quota specification
//
// swagger:model userQuota
type UserQuota struct {

	// User maximum build time in seconds
	// Example: 1800
	MaxBuildTime float64 `json:"maxBuildTime,omitempty"`

	// User cumulative build time per period in seconds
	// Example: 3600000
	MaxBuildTimeCumulative float64 `json:"maxBuildTimeCumulative,omitempty"`

	// User storage quota in MiB
	// Example: 1024
	MaxLibrarySize float64 `json:"maxLibrarySize,omitempty"`
}

// Validate validates this user quota
func (m *UserQuota) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user quota based on context it is used
func (m *UserQuota) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserQuota) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserQuota) UnmarshalBinary(b []byte) error {
	var res UserQuota
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
