version: "2"

run:
  concurrency: 2
  timeout: 5m
  build-tags:
    - apparmor
    - e2e_test
    - fakeroot_engine
    - libsubid
    - seccomp
    - selinux
    - singularity_engine
    - sylog

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - forcetypeassert
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - maintidx
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - reassign
    - revive
    - staticcheck
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: 'e2e/'
        linters:
          # The usetesting linter shows a lot of lint for env var handling and
          # tempdir creation in e2e tests. It's not really valid lint - the e2e
          # tests were explicitly written to keep tempdirs in a per-run outer dir,
          # and env var handling is complicated by the e2e.SingularityCmd
          # execution flow etc.
          - usetesting
      - linters:
        - gosec
      # G107 disallows making http calls to a URL stored in a variable
      # G204 disallows exec.Command() with a command/args stored in variables
      # G306 disallows creation of files with permissions greater than 0600
        text: "^(G107|G204|G306):"
      # We have numerous packages that clash with go stlib package names. They
      # can't be renamed without breaking pkg/ compatibility, which would need
      # a major version bump. Some, e.g. 'plugin' don't have an obvious
      # alternative name.
      - linters:
        - revive
        text: "var-naming: avoid package names that conflict with Go standard library package names"
      
    paths:
      - "internal/pkg/util/user/cgo_lookup_unix.go"

formatters:
  enable:
    - gofumpt
    - goimports
