FROM ubuntu:25.04

ARG GOVERSION="go1.26.0"
ARG GOOS="linux"
ARG GOARCH="amd64"
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
ENV DEBIAN_FRONTEND=noninteractive

# Install system packages
RUN apt-get -q update && apt-get -q install -y autoconf \
    automake \
    crun \
    cryptsetup \
    fuse2fs \
    fuse3 \
    fuse-overlayfs \
    git \
    libfuse3-dev \
    libglib2.0-dev \
    libseccomp-dev \
    libsubid-dev \
    libtool \
    make \
    pkg-config \
    squashfs-tools \
    squashfs-tools-ng \
    tzdata \
    uidmap \
    wget

# Install GO
RUN wget -O /tmp/go.tar.gz https://go.dev/dl/${GOVERSION}.${GOOS}-${GOARCH}.tar.gz && tar -C /usr/local -xzf /tmp/go.tar.gz

# Install SingularityCE
ADD . singularity-src

# Workaround for lack of gold linker on arm64
# See https://github.com/golang/go/issues/22040
RUN singularity-src/e2e/testdata/gold_workaround.sh

RUN cd singularity-src && git clean -fdx || true
RUN cd singularity-src && ./mconfig && make -C builddir && make -C builddir install

ENTRYPOINT ["/usr/local/bin/singularity"]
CMD ["version"]
