FROM ubuntu:24.10

ARG GOVERSION="go1.24.0"
ARG GOOS="linux"
ARG GOARCH="amd64"
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
ENV DEBIAN_FRONTEND=noninteractive

# Install system packages
RUN apt-get update && apt-get install -y autoconf \
    automake \
    crun \
    cryptsetup \
    fuse2fs \
    fuse \
    fuse-overlayfs \
    git \
    libfuse-dev \
    libglib2.0-dev \
    libseccomp-dev \
    libsubid-dev \
    libtool \
    make \
    pkg-config \
    squashfs-tools \
    squashfs-tools-ng \
    tzdata \
    uidmap \
    wget

# Install GO
RUN wget -O /tmp/go${GOLANG_VERSION}.linux-${ARCH}.tar.gz https://go.dev/dl/${GOVERSION}.${GOOS}-${GOARCH}.tar.gz && tar -C /usr/local -xzf /tmp/go${GOLANG_VERSION}.linux-${ARCH}.tar.gz

# Install SingularityCE
ADD . singularity
RUN cd singularity && git clean -fdx && ./mconfig && make -C builddir && make -C builddir install

ENTRYPOINT ["/usr/local/bin/singularity"]
CMD ["version"]