// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/keyservice/models"
)

// DeleteKeyReader is a Reader for the DeleteKey structure.
type DeleteKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteKeyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteKeyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteKeyForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteKeyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteKeyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteKeyOK creates a DeleteKeyOK with default headers values
func NewDeleteKeyOK() *DeleteKeyOK {
	return &DeleteKeyOK{}
}

/*
	DeleteKeyOK describes a response with status code 200, with default header values.

Success.
*/
type DeleteKeyOK struct {
}

func (o *DeleteKeyOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/key/{fingerprint}][%d] deleteKeyOK ", 200)
}

func (o *DeleteKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteKeyBadRequest creates a DeleteKeyBadRequest with default headers values
func NewDeleteKeyBadRequest() *DeleteKeyBadRequest {
	return &DeleteKeyBadRequest{}
}

/*
	DeleteKeyBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type DeleteKeyBadRequest struct {
	Payload *models.JSONError
}

func (o *DeleteKeyBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/key/{fingerprint}][%d] deleteKeyBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteKeyBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteKeyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteKeyUnauthorized creates a DeleteKeyUnauthorized with default headers values
func NewDeleteKeyUnauthorized() *DeleteKeyUnauthorized {
	return &DeleteKeyUnauthorized{}
}

/*
	DeleteKeyUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type DeleteKeyUnauthorized struct {
	Payload *models.JSONError
}

func (o *DeleteKeyUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/key/{fingerprint}][%d] deleteKeyUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteKeyUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteKeyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteKeyForbidden creates a DeleteKeyForbidden with default headers values
func NewDeleteKeyForbidden() *DeleteKeyForbidden {
	return &DeleteKeyForbidden{}
}

/*
	DeleteKeyForbidden describes a response with status code 403, with default header values.

Authorization token does not contain the Key Service Admin role.
*/
type DeleteKeyForbidden struct {
	Payload *models.JSONError
}

func (o *DeleteKeyForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/key/{fingerprint}][%d] deleteKeyForbidden  %+v", 403, o.Payload)
}
func (o *DeleteKeyForbidden) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteKeyForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteKeyNotFound creates a DeleteKeyNotFound with default headers values
func NewDeleteKeyNotFound() *DeleteKeyNotFound {
	return &DeleteKeyNotFound{}
}

/*
	DeleteKeyNotFound describes a response with status code 404, with default header values.

The specified key was not found.
*/
type DeleteKeyNotFound struct {
	Payload *models.JSONError
}

func (o *DeleteKeyNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/key/{fingerprint}][%d] deleteKeyNotFound  %+v", 404, o.Payload)
}
func (o *DeleteKeyNotFound) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteKeyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteKeyInternalServerError creates a DeleteKeyInternalServerError with default headers values
func NewDeleteKeyInternalServerError() *DeleteKeyInternalServerError {
	return &DeleteKeyInternalServerError{}
}

/*
	DeleteKeyInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteKeyInternalServerError struct {
	Payload *models.JSONError
}

func (o *DeleteKeyInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/key/{fingerprint}][%d] deleteKeyInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteKeyInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteKeyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
