// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/keyservice/models"
)

// GetKeyStatsReader is a Reader for the GetKeyStats structure.
type GetKeyStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKeyStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKeyStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetKeyStatsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetKeyStatsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetKeyStatsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetKeyStatsOK creates a GetKeyStatsOK with default headers values
func NewGetKeyStatsOK() *GetKeyStatsOK {
	return &GetKeyStatsOK{}
}

/*
	GetKeyStatsOK describes a response with status code 200, with default header values.

Success.
*/
type GetKeyStatsOK struct {
	Payload *models.KeyStatsResponse
}

func (o *GetKeyStatsOK) Error() string {
	return fmt.Sprintf("[GET /v1/stats/keys][%d] getKeyStatsOK  %+v", 200, o.Payload)
}
func (o *GetKeyStatsOK) GetPayload() *models.KeyStatsResponse {
	return o.Payload
}

func (o *GetKeyStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KeyStatsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKeyStatsUnauthorized creates a GetKeyStatsUnauthorized with default headers values
func NewGetKeyStatsUnauthorized() *GetKeyStatsUnauthorized {
	return &GetKeyStatsUnauthorized{}
}

/*
	GetKeyStatsUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type GetKeyStatsUnauthorized struct {
	Payload *models.JSONError
}

func (o *GetKeyStatsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/stats/keys][%d] getKeyStatsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetKeyStatsUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetKeyStatsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKeyStatsForbidden creates a GetKeyStatsForbidden with default headers values
func NewGetKeyStatsForbidden() *GetKeyStatsForbidden {
	return &GetKeyStatsForbidden{}
}

/*
	GetKeyStatsForbidden describes a response with status code 403, with default header values.

Authorization token does not contain the Key Service Admin role.
*/
type GetKeyStatsForbidden struct {
	Payload *models.JSONError
}

func (o *GetKeyStatsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/stats/keys][%d] getKeyStatsForbidden  %+v", 403, o.Payload)
}
func (o *GetKeyStatsForbidden) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetKeyStatsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKeyStatsInternalServerError creates a GetKeyStatsInternalServerError with default headers values
func NewGetKeyStatsInternalServerError() *GetKeyStatsInternalServerError {
	return &GetKeyStatsInternalServerError{}
}

/*
	GetKeyStatsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetKeyStatsInternalServerError struct {
	Payload *models.JSONError
}

func (o *GetKeyStatsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/stats/keys][%d] getKeyStatsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetKeyStatsInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetKeyStatsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
