// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/keyservice/models"
)

// ListKeysReader is a Reader for the ListKeys structure.
type ListKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListKeysBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListKeysUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListKeysInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListKeysOK creates a ListKeysOK with default headers values
func NewListKeysOK() *ListKeysOK {
	return &ListKeysOK{}
}

/*
	ListKeysOK describes a response with status code 200, with default header values.

Success.
*/
type ListKeysOK struct {
	Payload *models.KeysResponse
}

func (o *ListKeysOK) Error() string {
	return fmt.Sprintf("[GET /v1/keys][%d] listKeysOK  %+v", 200, o.Payload)
}
func (o *ListKeysOK) GetPayload() *models.KeysResponse {
	return o.Payload
}

func (o *ListKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KeysResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListKeysBadRequest creates a ListKeysBadRequest with default headers values
func NewListKeysBadRequest() *ListKeysBadRequest {
	return &ListKeysBadRequest{}
}

/*
	ListKeysBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type ListKeysBadRequest struct {
	Payload *models.JSONError
}

func (o *ListKeysBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/keys][%d] listKeysBadRequest  %+v", 400, o.Payload)
}
func (o *ListKeysBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ListKeysBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListKeysUnauthorized creates a ListKeysUnauthorized with default headers values
func NewListKeysUnauthorized() *ListKeysUnauthorized {
	return &ListKeysUnauthorized{}
}

/*
	ListKeysUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type ListKeysUnauthorized struct {
	Payload *models.JSONError
}

func (o *ListKeysUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/keys][%d] listKeysUnauthorized  %+v", 401, o.Payload)
}
func (o *ListKeysUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ListKeysUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListKeysInternalServerError creates a ListKeysInternalServerError with default headers values
func NewListKeysInternalServerError() *ListKeysInternalServerError {
	return &ListKeysInternalServerError{}
}

/*
	ListKeysInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type ListKeysInternalServerError struct {
	Payload *models.JSONError
}

func (o *ListKeysInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/keys][%d] listKeysInternalServerError  %+v", 500, o.Payload)
}
func (o *ListKeysInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ListKeysInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
