// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPksLookupParams creates a new PksLookupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPksLookupParams() *PksLookupParams {
	return &PksLookupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPksLookupParamsWithTimeout creates a new PksLookupParams object
// with the ability to set a timeout on a request.
func NewPksLookupParamsWithTimeout(timeout time.Duration) *PksLookupParams {
	return &PksLookupParams{
		timeout: timeout,
	}
}

// NewPksLookupParamsWithContext creates a new PksLookupParams object
// with the ability to set a context for a request.
func NewPksLookupParamsWithContext(ctx context.Context) *PksLookupParams {
	return &PksLookupParams{
		Context: ctx,
	}
}

// NewPksLookupParamsWithHTTPClient creates a new PksLookupParams object
// with the ability to set a custom HTTPClient for a request.
func NewPksLookupParamsWithHTTPClient(client *http.Client) *PksLookupParams {
	return &PksLookupParams{
		HTTPClient: client,
	}
}

/* PksLookupParams contains all the parameters to send to the API endpoint
   for the pks lookup operation.

   Typically these are written to a http.Request.
*/
type PksLookupParams struct {

	/* Op.

	   The operation to be performed on the keyserver. Supported values are "get", "index", and "vindex".
	*/
	Op string

	/* Search.

	   The ID of the key being sought, or some text from the key being sought.
	*/
	Search string

	/* XPagesize.

	   Maximum number of results to be returned.
	*/
	XPagesize *int64

	/* XPagetoken.

	   Token to next page of results.
	*/
	XPagetoken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pks lookup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PksLookupParams) WithDefaults() *PksLookupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pks lookup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PksLookupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pks lookup params
func (o *PksLookupParams) WithTimeout(timeout time.Duration) *PksLookupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pks lookup params
func (o *PksLookupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pks lookup params
func (o *PksLookupParams) WithContext(ctx context.Context) *PksLookupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pks lookup params
func (o *PksLookupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pks lookup params
func (o *PksLookupParams) WithHTTPClient(client *http.Client) *PksLookupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pks lookup params
func (o *PksLookupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOp adds the op to the pks lookup params
func (o *PksLookupParams) WithOp(op string) *PksLookupParams {
	o.SetOp(op)
	return o
}

// SetOp adds the op to the pks lookup params
func (o *PksLookupParams) SetOp(op string) {
	o.Op = op
}

// WithSearch adds the search to the pks lookup params
func (o *PksLookupParams) WithSearch(search string) *PksLookupParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the pks lookup params
func (o *PksLookupParams) SetSearch(search string) {
	o.Search = search
}

// WithXPagesize adds the xPagesize to the pks lookup params
func (o *PksLookupParams) WithXPagesize(xPagesize *int64) *PksLookupParams {
	o.SetXPagesize(xPagesize)
	return o
}

// SetXPagesize adds the xPagesize to the pks lookup params
func (o *PksLookupParams) SetXPagesize(xPagesize *int64) {
	o.XPagesize = xPagesize
}

// WithXPagetoken adds the xPagetoken to the pks lookup params
func (o *PksLookupParams) WithXPagetoken(xPagetoken *string) *PksLookupParams {
	o.SetXPagetoken(xPagetoken)
	return o
}

// SetXPagetoken adds the xPagetoken to the pks lookup params
func (o *PksLookupParams) SetXPagetoken(xPagetoken *string) {
	o.XPagetoken = xPagetoken
}

// WriteToRequest writes these params to a swagger request
func (o *PksLookupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param op
	qrOp := o.Op
	qOp := qrOp
	if qOp != "" {

		if err := r.SetQueryParam("op", qOp); err != nil {
			return err
		}
	}

	// query param search
	qrSearch := o.Search
	qSearch := qrSearch
	if qSearch != "" {

		if err := r.SetQueryParam("search", qSearch); err != nil {
			return err
		}
	}

	if o.XPagesize != nil {

		// query param x-pagesize
		var qrXPagesize int64

		if o.XPagesize != nil {
			qrXPagesize = *o.XPagesize
		}
		qXPagesize := swag.FormatInt64(qrXPagesize)
		if qXPagesize != "" {

			if err := r.SetQueryParam("x-pagesize", qXPagesize); err != nil {
				return err
			}
		}
	}

	if o.XPagetoken != nil {

		// query param x-pagetoken
		var qrXPagetoken string

		if o.XPagetoken != nil {
			qrXPagetoken = *o.XPagetoken
		}
		qXPagetoken := qrXPagetoken
		if qXPagetoken != "" {

			if err := r.SetQueryParam("x-pagetoken", qXPagetoken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
