// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPksAddParams creates a new PksAddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPksAddParams() *PksAddParams {
	return &PksAddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPksAddParamsWithTimeout creates a new PksAddParams object
// with the ability to set a timeout on a request.
func NewPksAddParamsWithTimeout(timeout time.Duration) *PksAddParams {
	return &PksAddParams{
		timeout: timeout,
	}
}

// NewPksAddParamsWithContext creates a new PksAddParams object
// with the ability to set a context for a request.
func NewPksAddParamsWithContext(ctx context.Context) *PksAddParams {
	return &PksAddParams{
		Context: ctx,
	}
}

// NewPksAddParamsWithHTTPClient creates a new PksAddParams object
// with the ability to set a custom HTTPClient for a request.
func NewPksAddParamsWithHTTPClient(client *http.Client) *PksAddParams {
	return &PksAddParams{
		HTTPClient: client,
	}
}

/* PksAddParams contains all the parameters to send to the API endpoint
   for the pks add operation.

   Typically these are written to a http.Request.
*/
type PksAddParams struct {

	/* Keytext.

	   A URL encoded, ASCII armored keyring.
	*/
	Keytext string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pks add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PksAddParams) WithDefaults() *PksAddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pks add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PksAddParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pks add params
func (o *PksAddParams) WithTimeout(timeout time.Duration) *PksAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pks add params
func (o *PksAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pks add params
func (o *PksAddParams) WithContext(ctx context.Context) *PksAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pks add params
func (o *PksAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pks add params
func (o *PksAddParams) WithHTTPClient(client *http.Client) *PksAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pks add params
func (o *PksAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKeytext adds the keytext to the pks add params
func (o *PksAddParams) WithKeytext(keytext string) *PksAddParams {
	o.SetKeytext(keytext)
	return o
}

// SetKeytext adds the keytext to the pks add params
func (o *PksAddParams) SetKeytext(keytext string) {
	o.Keytext = keytext
}

// WriteToRequest writes these params to a swagger request
func (o *PksAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param keytext
	frKeytext := o.Keytext
	fKeytext := frKeytext
	if fKeytext != "" {
		if err := r.SetFormParam("keytext", fKeytext); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
