// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/keyservice/models"
)

// PksAddReader is a Reader for the PksAdd structure.
type PksAddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PksAddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPksAddOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPksAddBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPksAddUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPksAddInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPksAddOK creates a PksAddOK with default headers values
func NewPksAddOK() *PksAddOK {
	return &PksAddOK{}
}

/*
	PksAddOK describes a response with status code 200, with default header values.

Success.
*/
type PksAddOK struct {
}

func (o *PksAddOK) Error() string {
	return fmt.Sprintf("[POST /pks/add][%d] pksAddOK ", 200)
}

func (o *PksAddOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPksAddBadRequest creates a PksAddBadRequest with default headers values
func NewPksAddBadRequest() *PksAddBadRequest {
	return &PksAddBadRequest{}
}

/*
	PksAddBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type PksAddBadRequest struct {
	Payload *models.JSONError
}

func (o *PksAddBadRequest) Error() string {
	return fmt.Sprintf("[POST /pks/add][%d] pksAddBadRequest  %+v", 400, o.Payload)
}
func (o *PksAddBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *PksAddBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPksAddUnauthorized creates a PksAddUnauthorized with default headers values
func NewPksAddUnauthorized() *PksAddUnauthorized {
	return &PksAddUnauthorized{}
}

/*
	PksAddUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type PksAddUnauthorized struct {
	Payload *models.JSONError
}

func (o *PksAddUnauthorized) Error() string {
	return fmt.Sprintf("[POST /pks/add][%d] pksAddUnauthorized  %+v", 401, o.Payload)
}
func (o *PksAddUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *PksAddUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPksAddInternalServerError creates a PksAddInternalServerError with default headers values
func NewPksAddInternalServerError() *PksAddInternalServerError {
	return &PksAddInternalServerError{}
}

/*
	PksAddInternalServerError describes a response with status code 500, with default header values.

Problem reading key text.
*/
type PksAddInternalServerError struct {
	Payload *models.JSONError
}

func (o *PksAddInternalServerError) Error() string {
	return fmt.Sprintf("[POST /pks/add][%d] pksAddInternalServerError  %+v", 500, o.Payload)
}
func (o *PksAddInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *PksAddInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
