// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildmanager/models"
)

// DeleteAgentReader is a Reader for the DeleteAgent structure.
type DeleteAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteAgentAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAgentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAgentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAgentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAgentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAgentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAgentAccepted creates a DeleteAgentAccepted with default headers values
func NewDeleteAgentAccepted() *DeleteAgentAccepted {
	return &DeleteAgentAccepted{}
}

/*
	DeleteAgentAccepted describes a response with status code 202, with default header values.

Success.
*/
type DeleteAgentAccepted struct {
}

func (o *DeleteAgentAccepted) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/agent-pool/{name}/{id}][%d] deleteAgentAccepted ", 202)
}

func (o *DeleteAgentAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAgentBadRequest creates a DeleteAgentBadRequest with default headers values
func NewDeleteAgentBadRequest() *DeleteAgentBadRequest {
	return &DeleteAgentBadRequest{}
}

/*
	DeleteAgentBadRequest describes a response with status code 400, with default header values.

Bad request.
*/
type DeleteAgentBadRequest struct {
	Payload *models.JSONError
}

func (o *DeleteAgentBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/agent-pool/{name}/{id}][%d] deleteAgentBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteAgentBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteAgentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentUnauthorized creates a DeleteAgentUnauthorized with default headers values
func NewDeleteAgentUnauthorized() *DeleteAgentUnauthorized {
	return &DeleteAgentUnauthorized{}
}

/*
	DeleteAgentUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type DeleteAgentUnauthorized struct {
	Payload *models.JSONError
}

func (o *DeleteAgentUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/agent-pool/{name}/{id}][%d] deleteAgentUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteAgentUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteAgentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentForbidden creates a DeleteAgentForbidden with default headers values
func NewDeleteAgentForbidden() *DeleteAgentForbidden {
	return &DeleteAgentForbidden{}
}

/*
	DeleteAgentForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type DeleteAgentForbidden struct {
	Payload *models.JSONError
}

func (o *DeleteAgentForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/agent-pool/{name}/{id}][%d] deleteAgentForbidden  %+v", 403, o.Payload)
}
func (o *DeleteAgentForbidden) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteAgentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentNotFound creates a DeleteAgentNotFound with default headers values
func NewDeleteAgentNotFound() *DeleteAgentNotFound {
	return &DeleteAgentNotFound{}
}

/*
	DeleteAgentNotFound describes a response with status code 404, with default header values.

Agent pool and/or agent ID not found.
*/
type DeleteAgentNotFound struct {
	Payload *models.JSONError
}

func (o *DeleteAgentNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/agent-pool/{name}/{id}][%d] deleteAgentNotFound  %+v", 404, o.Payload)
}
func (o *DeleteAgentNotFound) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteAgentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentInternalServerError creates a DeleteAgentInternalServerError with default headers values
func NewDeleteAgentInternalServerError() *DeleteAgentInternalServerError {
	return &DeleteAgentInternalServerError{}
}

/*
	DeleteAgentInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteAgentInternalServerError struct {
	Payload *models.JSONError
}

func (o *DeleteAgentInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/agent-pool/{name}/{id}][%d] deleteAgentInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteAgentInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteAgentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
