// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildmanager/models"
)

// GetAgentPoolReader is a Reader for the GetAgentPool structure.
type GetAgentPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAgentPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAgentPoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAgentPoolBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAgentPoolUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAgentPoolForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAgentPoolNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAgentPoolInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAgentPoolOK creates a GetAgentPoolOK with default headers values
func NewGetAgentPoolOK() *GetAgentPoolOK {
	return &GetAgentPoolOK{}
}

/*
	GetAgentPoolOK describes a response with status code 200, with default header values.

Success.
*/
type GetAgentPoolOK struct {
	Payload *models.AgentInfoList
}

func (o *GetAgentPoolOK) Error() string {
	return fmt.Sprintf("[GET /v1/admin/agent-pool/{name}][%d] getAgentPoolOK  %+v", 200, o.Payload)
}
func (o *GetAgentPoolOK) GetPayload() *models.AgentInfoList {
	return o.Payload
}

func (o *GetAgentPoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AgentInfoList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentPoolBadRequest creates a GetAgentPoolBadRequest with default headers values
func NewGetAgentPoolBadRequest() *GetAgentPoolBadRequest {
	return &GetAgentPoolBadRequest{}
}

/*
	GetAgentPoolBadRequest describes a response with status code 400, with default header values.

Bad request.
*/
type GetAgentPoolBadRequest struct {
	Payload *models.JSONError
}

func (o *GetAgentPoolBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/admin/agent-pool/{name}][%d] getAgentPoolBadRequest  %+v", 400, o.Payload)
}
func (o *GetAgentPoolBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetAgentPoolBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentPoolUnauthorized creates a GetAgentPoolUnauthorized with default headers values
func NewGetAgentPoolUnauthorized() *GetAgentPoolUnauthorized {
	return &GetAgentPoolUnauthorized{}
}

/*
	GetAgentPoolUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type GetAgentPoolUnauthorized struct {
	Payload *models.JSONError
}

func (o *GetAgentPoolUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/admin/agent-pool/{name}][%d] getAgentPoolUnauthorized  %+v", 401, o.Payload)
}
func (o *GetAgentPoolUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetAgentPoolUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentPoolForbidden creates a GetAgentPoolForbidden with default headers values
func NewGetAgentPoolForbidden() *GetAgentPoolForbidden {
	return &GetAgentPoolForbidden{}
}

/*
	GetAgentPoolForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type GetAgentPoolForbidden struct {
	Payload *models.JSONError
}

func (o *GetAgentPoolForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/admin/agent-pool/{name}][%d] getAgentPoolForbidden  %+v", 403, o.Payload)
}
func (o *GetAgentPoolForbidden) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetAgentPoolForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentPoolNotFound creates a GetAgentPoolNotFound with default headers values
func NewGetAgentPoolNotFound() *GetAgentPoolNotFound {
	return &GetAgentPoolNotFound{}
}

/*
	GetAgentPoolNotFound describes a response with status code 404, with default header values.

Agent pool not found.
*/
type GetAgentPoolNotFound struct {
	Payload *models.JSONError
}

func (o *GetAgentPoolNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/admin/agent-pool/{name}][%d] getAgentPoolNotFound  %+v", 404, o.Payload)
}
func (o *GetAgentPoolNotFound) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetAgentPoolNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentPoolInternalServerError creates a GetAgentPoolInternalServerError with default headers values
func NewGetAgentPoolInternalServerError() *GetAgentPoolInternalServerError {
	return &GetAgentPoolInternalServerError{}
}

/*
	GetAgentPoolInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetAgentPoolInternalServerError struct {
	Payload *models.JSONError
}

func (o *GetAgentPoolInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/admin/agent-pool/{name}][%d] getAgentPoolInternalServerError  %+v", 500, o.Payload)
}
func (o *GetAgentPoolInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetAgentPoolInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
