// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAgentPoolParams creates a new GetAgentPoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAgentPoolParams() *GetAgentPoolParams {
	return &GetAgentPoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAgentPoolParamsWithTimeout creates a new GetAgentPoolParams object
// with the ability to set a timeout on a request.
func NewGetAgentPoolParamsWithTimeout(timeout time.Duration) *GetAgentPoolParams {
	return &GetAgentPoolParams{
		timeout: timeout,
	}
}

// NewGetAgentPoolParamsWithContext creates a new GetAgentPoolParams object
// with the ability to set a context for a request.
func NewGetAgentPoolParamsWithContext(ctx context.Context) *GetAgentPoolParams {
	return &GetAgentPoolParams{
		Context: ctx,
	}
}

// NewGetAgentPoolParamsWithHTTPClient creates a new GetAgentPoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAgentPoolParamsWithHTTPClient(client *http.Client) *GetAgentPoolParams {
	return &GetAgentPoolParams{
		HTTPClient: client,
	}
}

/* GetAgentPoolParams contains all the parameters to send to the API endpoint
   for the get agent pool operation.

   Typically these are written to a http.Request.
*/
type GetAgentPoolParams struct {

	/* Name.

	   Name of Agent pool.
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get agent pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAgentPoolParams) WithDefaults() *GetAgentPoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get agent pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAgentPoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get agent pool params
func (o *GetAgentPoolParams) WithTimeout(timeout time.Duration) *GetAgentPoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get agent pool params
func (o *GetAgentPoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get agent pool params
func (o *GetAgentPoolParams) WithContext(ctx context.Context) *GetAgentPoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get agent pool params
func (o *GetAgentPoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get agent pool params
func (o *GetAgentPoolParams) WithHTTPClient(client *http.Client) *GetAgentPoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get agent pool params
func (o *GetAgentPoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get agent pool params
func (o *GetAgentPoolParams) WithName(name string) *GetAgentPoolParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get agent pool params
func (o *GetAgentPoolParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAgentPoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
