// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// GetRoleReader is a Reader for the GetRole structure.
type GetRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRoleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRoleOK creates a GetRoleOK with default headers values
func NewGetRoleOK() *GetRoleOK {
	return &GetRoleOK{}
}

/*
	GetRoleOK describes a response with status code 200, with default header values.

Success
*/
type GetRoleOK struct {
	Payload *models.RoleResponse
}

func (o *GetRoleOK) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles/{role}][%d] getRoleOK  %+v", 200, o.Payload)
}
func (o *GetRoleOK) GetPayload() *models.RoleResponse {
	return o.Payload
}

func (o *GetRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleBadRequest creates a GetRoleBadRequest with default headers values
func NewGetRoleBadRequest() *GetRoleBadRequest {
	return &GetRoleBadRequest{}
}

/*
	GetRoleBadRequest describes a response with status code 400, with default header values.

Bad request - role name not valid
*/
type GetRoleBadRequest struct {
	Payload *models.Json400error
}

func (o *GetRoleBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles/{role}][%d] getRoleBadRequest  %+v", 400, o.Payload)
}
func (o *GetRoleBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *GetRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleUnauthorized creates a GetRoleUnauthorized with default headers values
func NewGetRoleUnauthorized() *GetRoleUnauthorized {
	return &GetRoleUnauthorized{}
}

/*
	GetRoleUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type GetRoleUnauthorized struct {
	Payload *models.Json401error
}

func (o *GetRoleUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles/{role}][%d] getRoleUnauthorized  %+v", 401, o.Payload)
}
func (o *GetRoleUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *GetRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleNotFound creates a GetRoleNotFound with default headers values
func NewGetRoleNotFound() *GetRoleNotFound {
	return &GetRoleNotFound{}
}

/*
	GetRoleNotFound describes a response with status code 404, with default header values.

Bad request - role name not found
*/
type GetRoleNotFound struct {
	Payload *models.Json404error
}

func (o *GetRoleNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles/{role}][%d] getRoleNotFound  %+v", 404, o.Payload)
}
func (o *GetRoleNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *GetRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleInternalServerError creates a GetRoleInternalServerError with default headers values
func NewGetRoleInternalServerError() *GetRoleInternalServerError {
	return &GetRoleInternalServerError{}
}

/*
	GetRoleInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetRoleInternalServerError struct {
	Payload *models.Json500error
}

func (o *GetRoleInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles/{role}][%d] getRoleInternalServerError  %+v", 500, o.Payload)
}
func (o *GetRoleInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *GetRoleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
