// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// ListRolesReader is a Reader for the ListRoles structure.
type ListRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListRolesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListRolesOK creates a ListRolesOK with default headers values
func NewListRolesOK() *ListRolesOK {
	return &ListRolesOK{}
}

/*
	ListRolesOK describes a response with status code 200, with default header values.

Success
*/
type ListRolesOK struct {
	Payload *models.RoleListResponse
}

func (o *ListRolesOK) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles][%d] listRolesOK  %+v", 200, o.Payload)
}
func (o *ListRolesOK) GetPayload() *models.RoleListResponse {
	return o.Payload
}

func (o *ListRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRolesUnauthorized creates a ListRolesUnauthorized with default headers values
func NewListRolesUnauthorized() *ListRolesUnauthorized {
	return &ListRolesUnauthorized{}
}

/*
	ListRolesUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type ListRolesUnauthorized struct {
	Payload *models.Json401error
}

func (o *ListRolesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles][%d] listRolesUnauthorized  %+v", 401, o.Payload)
}
func (o *ListRolesUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *ListRolesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRolesInternalServerError creates a ListRolesInternalServerError with default headers values
func NewListRolesInternalServerError() *ListRolesInternalServerError {
	return &ListRolesInternalServerError{}
}

/*
	ListRolesInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ListRolesInternalServerError struct {
	Payload *models.Json500error
}

func (o *ListRolesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/admin/roles][%d] listRolesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListRolesInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *ListRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
