// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// BuildOutput Console output from a build.
// Example: Building Singularity image...\nSingularity container built: /tmp/5b3e30ac559f70000157df8a.simg\nCleaning up...\n
//
// swagger:model BuildOutput
type BuildOutput string

// Validate validates this build output
func (m BuildOutput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this build output based on context it is used
func (m BuildOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
