// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BuildRequest Metadata that describes a build request.
//
// swagger:model BuildRequest
type BuildRequest struct {

	// Raw build recipe
	// Example: Bootstrap: arch
	BuildRecipe string `json:"buildRecipe,omitempty"`

	// Callback URL to be called on build completion
	// Example: http://your.domain/build-completion-hook
	CallbackURL string `json:"callbackURL,omitempty"`

	// definition
	Definition *Definition `json:"definition,omitempty"`

	// The Container Library reference that the Builder will push the built image to. If not provided, the Builder will use an auto-generated reference.
	// Example: user/collection/name:tag
	LibraryRef string `json:"libraryRef,omitempty"`

	// URL of the Container Library that the Builder will push the built image to. If not provided, the Sylabs Container Library will be used.
	// Example: https://library.sylabs.io
	LibraryURL string `json:"libraryURL,omitempty"`
}

// Validate validates this build request
func (m *BuildRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefinition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildRequest) validateDefinition(formats strfmt.Registry) error {
	if swag.IsZero(m.Definition) { // not required
		return nil
	}

	if m.Definition != nil {
		if err := m.Definition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("definition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("definition")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this build request based on the context it is used
func (m *BuildRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDefinition(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildRequest) contextValidateDefinition(ctx context.Context, formats strfmt.Registry) error {

	if m.Definition != nil {
		if err := m.Definition.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("definition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("definition")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BuildRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildRequest) UnmarshalBinary(b []byte) error {
	var res BuildRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
