// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BuildStatsResponse Build statistics response.
//
// swagger:model BuildStatsResponse
type BuildStatsResponse struct {

	// data
	Data *BuildStatsResponseData `json:"data,omitempty"`
}

// Validate validates this build stats response
func (m *BuildStatsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildStatsResponse) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this build stats response based on the context it is used
func (m *BuildStatsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildStatsResponse) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if m.Data != nil {
		if err := m.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BuildStatsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildStatsResponse) UnmarshalBinary(b []byte) error {
	var res BuildStatsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BuildStatsResponseData build stats response data
//
// swagger:model BuildStatsResponseData
type BuildStatsResponseData struct {

	// build count
	// Example: 12345
	BuildCount int64 `json:"buildCount,omitempty"`

	// builds processing
	// Example: 4
	BuildsProcessing int64 `json:"buildsProcessing,omitempty"`

	// builds queued
	// Example: 6
	BuildsQueued int64 `json:"buildsQueued,omitempty"`

	// users with builds
	// Example: 9876
	UsersWithBuilds int64 `json:"usersWithBuilds,omitempty"`
}

// Validate validates this build stats response data
func (m *BuildStatsResponseData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this build stats response data based on context it is used
func (m *BuildStatsResponseData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BuildStatsResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildStatsResponseData) UnmarshalBinary(b []byte) error {
	var res BuildStatsResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
