// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BuildMetadata Metadata that describes a build.
//
// swagger:model BuildMetadata
type BuildMetadata struct {

	// Raw build recipe
	// Example: Bootstrap: arch
	BuildRecipe string `json:"buildRecipe,omitempty"`

	// Callback URL to be called on build completion
	// Example: http://your.domain/build-completion-hook
	CallbackURL string `json:"callbackURL,omitempty"`

	// Time at which the build was completed
	// Example: 2018-05-07T14:06:22.5742348Z
	CompleteTime string `json:"completeTime,omitempty"`

	// The user that created the build
	// Example: user
	CreatedBy string `json:"createdBy,omitempty"`

	// definition
	Definition *Definition `json:"definition,omitempty"`

	// whether build is deleted or not
	// Example: true
	Deleted bool `json:"deleted,omitempty"`

	// Unique BSON identifier for this object
	// Example: 5af05d5e9293620001b41d2c
	ID string `json:"id,omitempty"`

	// Checksum of the image file
	// Example: sha256.d86de0781ebd9e4d95c1c79b3387b563c90b0db3d3f6d77440c31127582f52bc
	ImageChecksum string `json:"imageChecksum,omitempty"`

	// Size of the image file, in bytes
	// Example: 350411
	ImageSize int64 `json:"imageSize,omitempty"`

	// If TRUE, indicates the build is complete
	// Example: true
	IsComplete bool `json:"isComplete,omitempty"`

	// The Container Library reference of the built image.
	// Example: user/collection/name:tag
	LibraryRef string `json:"libraryRef,omitempty"`

	// URL of the Container Library that the Builder will push the built image to.
	// Example: https://library.sylabs.io
	LibraryURL string `json:"libraryURL,omitempty"`

	// Time at which the build was started
	// Example: 2018-05-07T14:06:22.5742348Z
	StartTime string `json:"startTime,omitempty"`

	// Indicates build status
	// Example: InProgress
	// Enum: [Pending InProgress Complete Cancelled Deleted]
	Status string `json:"status,omitempty"`

	// Time at which the build was submitted
	// Example: 2018-05-07T14:06:22.5742348Z
	SubmitTime string `json:"submitTime,omitempty"`

	// URL of websocket to monitor console output as build progresses
	// Example: http://localhost:5051/build-ws/5af05d5e9293620001b41d2c
	WsURL string `json:"wsURL,omitempty"`
}

// Validate validates this build metadata
func (m *BuildMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefinition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildMetadata) validateDefinition(formats strfmt.Registry) error {
	if swag.IsZero(m.Definition) { // not required
		return nil
	}

	if m.Definition != nil {
		if err := m.Definition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("definition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("definition")
			}
			return err
		}
	}

	return nil
}

var buildMetadataTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Pending","InProgress","Complete","Cancelled","Deleted"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		buildMetadataTypeStatusPropEnum = append(buildMetadataTypeStatusPropEnum, v)
	}
}

const (

	// BuildMetadataStatusPending captures enum value "Pending"
	BuildMetadataStatusPending string = "Pending"

	// BuildMetadataStatusInProgress captures enum value "InProgress"
	BuildMetadataStatusInProgress string = "InProgress"

	// BuildMetadataStatusComplete captures enum value "Complete"
	BuildMetadataStatusComplete string = "Complete"

	// BuildMetadataStatusCancelled captures enum value "Cancelled"
	BuildMetadataStatusCancelled string = "Cancelled"

	// BuildMetadataStatusDeleted captures enum value "Deleted"
	BuildMetadataStatusDeleted string = "Deleted"
)

// prop value enum
func (m *BuildMetadata) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, buildMetadataTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BuildMetadata) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this build metadata based on the context it is used
func (m *BuildMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDefinition(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildMetadata) contextValidateDefinition(ctx context.Context, formats strfmt.Registry) error {

	if m.Definition != nil {
		if err := m.Definition.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("definition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("definition")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BuildMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildMetadata) UnmarshalBinary(b []byte) error {
	var res BuildMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
