// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DefFile Raw DefFile
// Example: Bootstrap: arch
//
// swagger:model DefFile
type DefFile string

// Validate validates this def file
func (m DefFile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this def file based on context it is used
func (m DefFile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
