// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Definition Description of a build request.
//
// swagger:model Definition
type Definition struct {

	// build data
	BuildData *DefinitionBuildData `json:"buildData,omitempty"`

	// header
	Header *DefinitionHeader `json:"header,omitempty"`

	// image data
	ImageData *DefinitionImageData `json:"imageData,omitempty"`
}

// Validate validates this definition
func (m *Definition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuildData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHeader(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Definition) validateBuildData(formats strfmt.Registry) error {
	if swag.IsZero(m.BuildData) { // not required
		return nil
	}

	if m.BuildData != nil {
		if err := m.BuildData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buildData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("buildData")
			}
			return err
		}
	}

	return nil
}

func (m *Definition) validateHeader(formats strfmt.Registry) error {
	if swag.IsZero(m.Header) { // not required
		return nil
	}

	if m.Header != nil {
		if err := m.Header.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("header")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("header")
			}
			return err
		}
	}

	return nil
}

func (m *Definition) validateImageData(formats strfmt.Registry) error {
	if swag.IsZero(m.ImageData) { // not required
		return nil
	}

	if m.ImageData != nil {
		if err := m.ImageData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("imageData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("imageData")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this definition based on the context it is used
func (m *Definition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBuildData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHeader(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImageData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Definition) contextValidateBuildData(ctx context.Context, formats strfmt.Registry) error {

	if m.BuildData != nil {
		if err := m.BuildData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buildData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("buildData")
			}
			return err
		}
	}

	return nil
}

func (m *Definition) contextValidateHeader(ctx context.Context, formats strfmt.Registry) error {

	if m.Header != nil {
		if err := m.Header.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("header")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("header")
			}
			return err
		}
	}

	return nil
}

func (m *Definition) contextValidateImageData(ctx context.Context, formats strfmt.Registry) error {

	if m.ImageData != nil {
		if err := m.ImageData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("imageData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("imageData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Definition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Definition) UnmarshalBinary(b []byte) error {
	var res Definition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DefinitionBuildData definition build data
//
// swagger:model DefinitionBuildData
type DefinitionBuildData struct {

	// build scripts
	BuildScripts *DefinitionBuildDataBuildScripts `json:"buildScripts,omitempty"`

	// files
	Files map[string]string `json:"files,omitempty"`
}

// Validate validates this definition build data
func (m *DefinitionBuildData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuildScripts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DefinitionBuildData) validateBuildScripts(formats strfmt.Registry) error {
	if swag.IsZero(m.BuildScripts) { // not required
		return nil
	}

	if m.BuildScripts != nil {
		if err := m.BuildScripts.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buildData" + "." + "buildScripts")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("buildData" + "." + "buildScripts")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this definition build data based on the context it is used
func (m *DefinitionBuildData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBuildScripts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DefinitionBuildData) contextValidateBuildScripts(ctx context.Context, formats strfmt.Registry) error {

	if m.BuildScripts != nil {
		if err := m.BuildScripts.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buildData" + "." + "buildScripts")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("buildData" + "." + "buildScripts")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DefinitionBuildData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefinitionBuildData) UnmarshalBinary(b []byte) error {
	var res DefinitionBuildData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DefinitionBuildDataBuildScripts definition build data build scripts
//
// swagger:model DefinitionBuildDataBuildScripts
type DefinitionBuildDataBuildScripts struct {

	// Commands that are executed within the container after the base OS has been installed at build time.
	// Example: echo 'Post command!'
	Post string `json:"post,omitempty"`

	// Commands that are executed on the host system outside of the container after the base OS has been installed.
	// Example: echo 'Setup command!'
	Setup string `json:"setup,omitempty"`
}

// Validate validates this definition build data build scripts
func (m *DefinitionBuildDataBuildScripts) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this definition build data build scripts based on context it is used
func (m *DefinitionBuildDataBuildScripts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefinitionBuildDataBuildScripts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefinitionBuildDataBuildScripts) UnmarshalBinary(b []byte) error {
	var res DefinitionBuildDataBuildScripts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DefinitionHeader definition header
//
// swagger:model DefinitionHeader
type DefinitionHeader struct {

	// The kind of base to use.
	// Example: docker
	Bootstrap string `json:"bootstrap,omitempty"`

	// The named container reference.
	// Example: ubuntu
	From string `json:"from,omitempty"`
}

// Validate validates this definition header
func (m *DefinitionHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this definition header based on context it is used
func (m *DefinitionHeader) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefinitionHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefinitionHeader) UnmarshalBinary(b []byte) error {
	var res DefinitionHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DefinitionImageData definition image data
//
// swagger:model DefinitionImageData
type DefinitionImageData struct {

	// image scripts
	ImageScripts *DefinitionImageDataImageScripts `json:"imageScripts,omitempty"`
}

// Validate validates this definition image data
func (m *DefinitionImageData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImageScripts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DefinitionImageData) validateImageScripts(formats strfmt.Registry) error {
	if swag.IsZero(m.ImageScripts) { // not required
		return nil
	}

	if m.ImageScripts != nil {
		if err := m.ImageScripts.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("imageData" + "." + "imageScripts")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("imageData" + "." + "imageScripts")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this definition image data based on the context it is used
func (m *DefinitionImageData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateImageScripts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DefinitionImageData) contextValidateImageScripts(ctx context.Context, formats strfmt.Registry) error {

	if m.ImageScripts != nil {
		if err := m.ImageScripts.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("imageData" + "." + "imageScripts")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("imageData" + "." + "imageScripts")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DefinitionImageData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefinitionImageData) UnmarshalBinary(b []byte) error {
	var res DefinitionImageData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DefinitionImageDataImageScripts definition image data image scripts
//
// swagger:model DefinitionImageDataImageScripts
type DefinitionImageDataImageScripts struct {

	// Environment variables that are exposed when the container image is run.
	// Example: FOO=bar
	Environment string `json:"environment,omitempty"`

	// Some helpful message!
	// Example: Help message for the container image.
	Help string `json:"help,omitempty"`

	// Script that is executed when the container image is run.
	// Example: echo 'Hello, Singularity world!'
	RunScript string `json:"runScript,omitempty"`

	// Test script that is run on build completion.
	// Example: echo 'Test command!'
	Test string `json:"test,omitempty"`
}

// Validate validates this definition image data image scripts
func (m *DefinitionImageDataImageScripts) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this definition image data image scripts based on context it is used
func (m *DefinitionImageDataImageScripts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefinitionImageDataImageScripts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefinitionImageDataImageScripts) UnmarshalBinary(b []byte) error {
	var res DefinitionImageDataImageScripts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
