// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/client/base"
	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/client/groups"
	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/client/roles"
	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/client/users"
)

// Default sylabs consent service API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "auth.sylabs.io:3000"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new sylabs consent service API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *SylabsConsentServiceAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new sylabs consent service API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *SylabsConsentServiceAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new sylabs consent service API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *SylabsConsentServiceAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(SylabsConsentServiceAPI)
	cli.Transport = transport
	cli.Base = base.New(transport, formats)
	cli.Groups = groups.New(transport, formats)
	cli.Roles = roles.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// SylabsConsentServiceAPI is a client for sylabs consent service API
type SylabsConsentServiceAPI struct {
	Base base.ClientService

	Groups groups.ClientService

	Roles roles.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *SylabsConsentServiceAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Base.SetTransport(transport)
	c.Groups.SetTransport(transport)
	c.Roles.SetTransport(transport)
	c.Users.SetTransport(transport)
}
