// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// NewAddBuildParams creates a new AddBuildParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddBuildParams() *AddBuildParams {
	return &AddBuildParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddBuildParamsWithTimeout creates a new AddBuildParams object
// with the ability to set a timeout on a request.
func NewAddBuildParamsWithTimeout(timeout time.Duration) *AddBuildParams {
	return &AddBuildParams{
		timeout: timeout,
	}
}

// NewAddBuildParamsWithContext creates a new AddBuildParams object
// with the ability to set a context for a request.
func NewAddBuildParamsWithContext(ctx context.Context) *AddBuildParams {
	return &AddBuildParams{
		Context: ctx,
	}
}

// NewAddBuildParamsWithHTTPClient creates a new AddBuildParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddBuildParamsWithHTTPClient(client *http.Client) *AddBuildParams {
	return &AddBuildParams{
		HTTPClient: client,
	}
}

/*
AddBuildParams contains all the parameters to send to the API endpoint

	for the add build operation.

	Typically these are written to a http.Request.
*/
type AddBuildParams struct {

	// BuildRequest.
	BuildRequest *models.BuildRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add build params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBuildParams) WithDefaults() *AddBuildParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add build params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBuildParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add build params
func (o *AddBuildParams) WithTimeout(timeout time.Duration) *AddBuildParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add build params
func (o *AddBuildParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add build params
func (o *AddBuildParams) WithContext(ctx context.Context) *AddBuildParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add build params
func (o *AddBuildParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add build params
func (o *AddBuildParams) WithHTTPClient(client *http.Client) *AddBuildParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add build params
func (o *AddBuildParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildRequest adds the buildRequest to the add build params
func (o *AddBuildParams) WithBuildRequest(buildRequest *models.BuildRequest) *AddBuildParams {
	o.SetBuildRequest(buildRequest)
	return o
}

// SetBuildRequest adds the buildRequest to the add build params
func (o *AddBuildParams) SetBuildRequest(buildRequest *models.BuildRequest) {
	o.BuildRequest = buildRequest
}

// WriteToRequest writes these params to a swagger request
func (o *AddBuildParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.BuildRequest != nil {
		if err := r.SetBodyParam(o.BuildRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
