// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// AddBuildReader is a Reader for the AddBuild structure.
type AddBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddBuildOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddBuildBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddBuildUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddBuildInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddBuildOK creates a AddBuildOK with default headers values
func NewAddBuildOK() *AddBuildOK {
	return &AddBuildOK{}
}

/*
	AddBuildOK describes a response with status code 200, with default header values.

Success. Build request accepted.
*/
type AddBuildOK struct {
	Payload *models.BuildMetadataResponse
}

func (o *AddBuildOK) Error() string {
	return fmt.Sprintf("[POST /v1/build][%d] addBuildOK  %+v", 200, o.Payload)
}
func (o *AddBuildOK) GetPayload() *models.BuildMetadataResponse {
	return o.Payload
}

func (o *AddBuildOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BuildMetadataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddBuildBadRequest creates a AddBuildBadRequest with default headers values
func NewAddBuildBadRequest() *AddBuildBadRequest {
	return &AddBuildBadRequest{}
}

/*
	AddBuildBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure build parameters are properly formatted.
*/
type AddBuildBadRequest struct {
	Payload *models.JSONError
}

func (o *AddBuildBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/build][%d] addBuildBadRequest  %+v", 400, o.Payload)
}
func (o *AddBuildBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AddBuildBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddBuildUnauthorized creates a AddBuildUnauthorized with default headers values
func NewAddBuildUnauthorized() *AddBuildUnauthorized {
	return &AddBuildUnauthorized{}
}

/*
	AddBuildUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type AddBuildUnauthorized struct {
	Payload *models.JSONError
}

func (o *AddBuildUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/build][%d] addBuildUnauthorized  %+v", 401, o.Payload)
}
func (o *AddBuildUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AddBuildUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddBuildInternalServerError creates a AddBuildInternalServerError with default headers values
func NewAddBuildInternalServerError() *AddBuildInternalServerError {
	return &AddBuildInternalServerError{}
}

/*
	AddBuildInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type AddBuildInternalServerError struct {
	Payload *models.JSONError
}

func (o *AddBuildInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/build][%d] addBuildInternalServerError  %+v", 500, o.Payload)
}
func (o *AddBuildInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AddBuildInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
