// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// AddBuildLegacyReader is a Reader for the AddBuildLegacy structure.
type AddBuildLegacyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddBuildLegacyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddBuildLegacyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddBuildLegacyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddBuildLegacyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddBuildLegacyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddBuildLegacyOK creates a AddBuildLegacyOK with default headers values
func NewAddBuildLegacyOK() *AddBuildLegacyOK {
	return &AddBuildLegacyOK{}
}

/*
	AddBuildLegacyOK describes a response with status code 200, with default header values.

Success. Build request accepted.
*/
type AddBuildLegacyOK struct {
	Payload *models.BuildMetadataResponse
}

func (o *AddBuildLegacyOK) Error() string {
	return fmt.Sprintf("[POST /v1/build-def-file][%d] addBuildLegacyOK  %+v", 200, o.Payload)
}
func (o *AddBuildLegacyOK) GetPayload() *models.BuildMetadataResponse {
	return o.Payload
}

func (o *AddBuildLegacyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BuildMetadataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddBuildLegacyBadRequest creates a AddBuildLegacyBadRequest with default headers values
func NewAddBuildLegacyBadRequest() *AddBuildLegacyBadRequest {
	return &AddBuildLegacyBadRequest{}
}

/*
	AddBuildLegacyBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure DefFile is properly formatted.
*/
type AddBuildLegacyBadRequest struct {
	Payload *models.JSONError
}

func (o *AddBuildLegacyBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/build-def-file][%d] addBuildLegacyBadRequest  %+v", 400, o.Payload)
}
func (o *AddBuildLegacyBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AddBuildLegacyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddBuildLegacyUnauthorized creates a AddBuildLegacyUnauthorized with default headers values
func NewAddBuildLegacyUnauthorized() *AddBuildLegacyUnauthorized {
	return &AddBuildLegacyUnauthorized{}
}

/*
	AddBuildLegacyUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type AddBuildLegacyUnauthorized struct {
	Payload *models.JSONError
}

func (o *AddBuildLegacyUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/build-def-file][%d] addBuildLegacyUnauthorized  %+v", 401, o.Payload)
}
func (o *AddBuildLegacyUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AddBuildLegacyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddBuildLegacyInternalServerError creates a AddBuildLegacyInternalServerError with default headers values
func NewAddBuildLegacyInternalServerError() *AddBuildLegacyInternalServerError {
	return &AddBuildLegacyInternalServerError{}
}

/*
	AddBuildLegacyInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type AddBuildLegacyInternalServerError struct {
	Payload *models.JSONError
}

func (o *AddBuildLegacyInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/build-def-file][%d] addBuildLegacyInternalServerError  %+v", 500, o.Payload)
}
func (o *AddBuildLegacyInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AddBuildLegacyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
