// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// CancelBuildReader is a Reader for the CancelBuild structure.
type CancelBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCancelBuildNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCancelBuildBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCancelBuildUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCancelBuildNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCancelBuildInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCancelBuildNoContent creates a CancelBuildNoContent with default headers values
func NewCancelBuildNoContent() *CancelBuildNoContent {
	return &CancelBuildNoContent{}
}

/*
	CancelBuildNoContent describes a response with status code 204, with default header values.

Success.
*/
type CancelBuildNoContent struct {
}

func (o *CancelBuildNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/build/{id}/_cancel][%d] cancelBuildNoContent ", 204)
}

func (o *CancelBuildNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCancelBuildBadRequest creates a CancelBuildBadRequest with default headers values
func NewCancelBuildBadRequest() *CancelBuildBadRequest {
	return &CancelBuildBadRequest{}
}

/*
	CancelBuildBadRequest describes a response with status code 400, with default header values.

Bad request.
*/
type CancelBuildBadRequest struct {
	Payload *models.JSONError
}

func (o *CancelBuildBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/build/{id}/_cancel][%d] cancelBuildBadRequest  %+v", 400, o.Payload)
}
func (o *CancelBuildBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *CancelBuildBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelBuildUnauthorized creates a CancelBuildUnauthorized with default headers values
func NewCancelBuildUnauthorized() *CancelBuildUnauthorized {
	return &CancelBuildUnauthorized{}
}

/*
	CancelBuildUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type CancelBuildUnauthorized struct {
	Payload *models.JSONError
}

func (o *CancelBuildUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/build/{id}/_cancel][%d] cancelBuildUnauthorized  %+v", 401, o.Payload)
}
func (o *CancelBuildUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *CancelBuildUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelBuildNotFound creates a CancelBuildNotFound with default headers values
func NewCancelBuildNotFound() *CancelBuildNotFound {
	return &CancelBuildNotFound{}
}

/*
	CancelBuildNotFound describes a response with status code 404, with default header values.

Not found. The supplied build ID was not found.
*/
type CancelBuildNotFound struct {
	Payload *models.JSONError
}

func (o *CancelBuildNotFound) Error() string {
	return fmt.Sprintf("[PUT /v1/build/{id}/_cancel][%d] cancelBuildNotFound  %+v", 404, o.Payload)
}
func (o *CancelBuildNotFound) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *CancelBuildNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelBuildInternalServerError creates a CancelBuildInternalServerError with default headers values
func NewCancelBuildInternalServerError() *CancelBuildInternalServerError {
	return &CancelBuildInternalServerError{}
}

/*
	CancelBuildInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type CancelBuildInternalServerError struct {
	Payload *models.JSONError
}

func (o *CancelBuildInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/build/{id}/_cancel][%d] cancelBuildInternalServerError  %+v", 500, o.Payload)
}
func (o *CancelBuildInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *CancelBuildInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
