// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// ConvertDefFileReader is a Reader for the ConvertDefFile structure.
type ConvertDefFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConvertDefFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConvertDefFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewConvertDefFileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewConvertDefFileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewConvertDefFileInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewConvertDefFileOK creates a ConvertDefFileOK with default headers values
func NewConvertDefFileOK() *ConvertDefFileOK {
	return &ConvertDefFileOK{}
}

/*
	ConvertDefFileOK describes a response with status code 200, with default header values.

Success.
*/
type ConvertDefFileOK struct {
	Payload *models.DefinitionResponse
}

func (o *ConvertDefFileOK) Error() string {
	return fmt.Sprintf("[POST /v1/convert-def-file][%d] convertDefFileOK  %+v", 200, o.Payload)
}
func (o *ConvertDefFileOK) GetPayload() *models.DefinitionResponse {
	return o.Payload
}

func (o *ConvertDefFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefinitionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConvertDefFileBadRequest creates a ConvertDefFileBadRequest with default headers values
func NewConvertDefFileBadRequest() *ConvertDefFileBadRequest {
	return &ConvertDefFileBadRequest{}
}

/*
	ConvertDefFileBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure DefFile is properly formatted.
*/
type ConvertDefFileBadRequest struct {
	Payload *models.JSONError
}

func (o *ConvertDefFileBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/convert-def-file][%d] convertDefFileBadRequest  %+v", 400, o.Payload)
}
func (o *ConvertDefFileBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ConvertDefFileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConvertDefFileUnauthorized creates a ConvertDefFileUnauthorized with default headers values
func NewConvertDefFileUnauthorized() *ConvertDefFileUnauthorized {
	return &ConvertDefFileUnauthorized{}
}

/*
	ConvertDefFileUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type ConvertDefFileUnauthorized struct {
	Payload *models.JSONError
}

func (o *ConvertDefFileUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/convert-def-file][%d] convertDefFileUnauthorized  %+v", 401, o.Payload)
}
func (o *ConvertDefFileUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ConvertDefFileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConvertDefFileInternalServerError creates a ConvertDefFileInternalServerError with default headers values
func NewConvertDefFileInternalServerError() *ConvertDefFileInternalServerError {
	return &ConvertDefFileInternalServerError{}
}

/*
	ConvertDefFileInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type ConvertDefFileInternalServerError struct {
	Payload *models.JSONError
}

func (o *ConvertDefFileInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/convert-def-file][%d] convertDefFileInternalServerError  %+v", 500, o.Payload)
}
func (o *ConvertDefFileInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ConvertDefFileInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
