// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// NewConvertDefFileParams creates a new ConvertDefFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConvertDefFileParams() *ConvertDefFileParams {
	return &ConvertDefFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewConvertDefFileParamsWithTimeout creates a new ConvertDefFileParams object
// with the ability to set a timeout on a request.
func NewConvertDefFileParamsWithTimeout(timeout time.Duration) *ConvertDefFileParams {
	return &ConvertDefFileParams{
		timeout: timeout,
	}
}

// NewConvertDefFileParamsWithContext creates a new ConvertDefFileParams object
// with the ability to set a context for a request.
func NewConvertDefFileParamsWithContext(ctx context.Context) *ConvertDefFileParams {
	return &ConvertDefFileParams{
		Context: ctx,
	}
}

// NewConvertDefFileParamsWithHTTPClient creates a new ConvertDefFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewConvertDefFileParamsWithHTTPClient(client *http.Client) *ConvertDefFileParams {
	return &ConvertDefFileParams{
		HTTPClient: client,
	}
}

/*
ConvertDefFileParams contains all the parameters to send to the API endpoint

	for the convert def file operation.

	Typically these are written to a http.Request.
*/
type ConvertDefFileParams struct {

	// DefFile.
	DefFile models.DefFile

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the convert def file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConvertDefFileParams) WithDefaults() *ConvertDefFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the convert def file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConvertDefFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the convert def file params
func (o *ConvertDefFileParams) WithTimeout(timeout time.Duration) *ConvertDefFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the convert def file params
func (o *ConvertDefFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the convert def file params
func (o *ConvertDefFileParams) WithContext(ctx context.Context) *ConvertDefFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the convert def file params
func (o *ConvertDefFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the convert def file params
func (o *ConvertDefFileParams) WithHTTPClient(client *http.Client) *ConvertDefFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the convert def file params
func (o *ConvertDefFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDefFile adds the defFile to the convert def file params
func (o *ConvertDefFileParams) WithDefFile(defFile models.DefFile) *ConvertDefFileParams {
	o.SetDefFile(defFile)
	return o
}

// SetDefFile adds the defFile to the convert def file params
func (o *ConvertDefFileParams) SetDefFile(defFile models.DefFile) {
	o.DefFile = defFile
}

// WriteToRequest writes these params to a swagger request
func (o *ConvertDefFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.DefFile); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
