// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteBuildParams creates a new DeleteBuildParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBuildParams() *DeleteBuildParams {
	return &DeleteBuildParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBuildParamsWithTimeout creates a new DeleteBuildParams object
// with the ability to set a timeout on a request.
func NewDeleteBuildParamsWithTimeout(timeout time.Duration) *DeleteBuildParams {
	return &DeleteBuildParams{
		timeout: timeout,
	}
}

// NewDeleteBuildParamsWithContext creates a new DeleteBuildParams object
// with the ability to set a context for a request.
func NewDeleteBuildParamsWithContext(ctx context.Context) *DeleteBuildParams {
	return &DeleteBuildParams{
		Context: ctx,
	}
}

// NewDeleteBuildParamsWithHTTPClient creates a new DeleteBuildParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBuildParamsWithHTTPClient(client *http.Client) *DeleteBuildParams {
	return &DeleteBuildParams{
		HTTPClient: client,
	}
}

/* DeleteBuildParams contains all the parameters to send to the API endpoint
   for the delete build operation.

   Typically these are written to a http.Request.
*/
type DeleteBuildParams struct {

	/* ID.

	   Unique BSON ID of a build.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete build params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBuildParams) WithDefaults() *DeleteBuildParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete build params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBuildParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete build params
func (o *DeleteBuildParams) WithTimeout(timeout time.Duration) *DeleteBuildParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete build params
func (o *DeleteBuildParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete build params
func (o *DeleteBuildParams) WithContext(ctx context.Context) *DeleteBuildParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete build params
func (o *DeleteBuildParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete build params
func (o *DeleteBuildParams) WithHTTPClient(client *http.Client) *DeleteBuildParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete build params
func (o *DeleteBuildParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete build params
func (o *DeleteBuildParams) WithID(id string) *DeleteBuildParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete build params
func (o *DeleteBuildParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBuildParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
