// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// DeleteBuildReader is a Reader for the DeleteBuild structure.
type DeleteBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteBuildOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteBuildBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteBuildUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteBuildInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteBuildOK creates a DeleteBuildOK with default headers values
func NewDeleteBuildOK() *DeleteBuildOK {
	return &DeleteBuildOK{}
}

/*
	DeleteBuildOK describes a response with status code 200, with default header values.

Success.
*/
type DeleteBuildOK struct {
}

func (o *DeleteBuildOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/build/{id}][%d] deleteBuildOK ", 200)
}

func (o *DeleteBuildOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBuildBadRequest creates a DeleteBuildBadRequest with default headers values
func NewDeleteBuildBadRequest() *DeleteBuildBadRequest {
	return &DeleteBuildBadRequest{}
}

/*
	DeleteBuildBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure build ID is properly formatted.
*/
type DeleteBuildBadRequest struct {
	Payload *models.JSONError
}

func (o *DeleteBuildBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/build/{id}][%d] deleteBuildBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteBuildBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteBuildBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBuildUnauthorized creates a DeleteBuildUnauthorized with default headers values
func NewDeleteBuildUnauthorized() *DeleteBuildUnauthorized {
	return &DeleteBuildUnauthorized{}
}

/*
	DeleteBuildUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type DeleteBuildUnauthorized struct {
	Payload *models.JSONError
}

func (o *DeleteBuildUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/build/{id}][%d] deleteBuildUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteBuildUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteBuildUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBuildInternalServerError creates a DeleteBuildInternalServerError with default headers values
func NewDeleteBuildInternalServerError() *DeleteBuildInternalServerError {
	return &DeleteBuildInternalServerError{}
}

/*
	DeleteBuildInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteBuildInternalServerError struct {
	Payload *models.JSONError
}

func (o *DeleteBuildInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/build/{id}][%d] deleteBuildInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteBuildInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DeleteBuildInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
