// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// GetBuildOutputReader is a Reader for the GetBuildOutput structure.
type GetBuildOutputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBuildOutputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBuildOutputOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBuildOutputUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBuildOutputNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBuildOutputInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBuildOutputOK creates a GetBuildOutputOK with default headers values
func NewGetBuildOutputOK() *GetBuildOutputOK {
	return &GetBuildOutputOK{}
}

/*
	GetBuildOutputOK describes a response with status code 200, with default header values.

Success.
*/
type GetBuildOutputOK struct {
	Payload models.BuildOutput
}

func (o *GetBuildOutputOK) Error() string {
	return fmt.Sprintf("[GET /v1/build-output/{id}][%d] getBuildOutputOK  %+v", 200, o.Payload)
}
func (o *GetBuildOutputOK) GetPayload() models.BuildOutput {
	return o.Payload
}

func (o *GetBuildOutputOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildOutputUnauthorized creates a GetBuildOutputUnauthorized with default headers values
func NewGetBuildOutputUnauthorized() *GetBuildOutputUnauthorized {
	return &GetBuildOutputUnauthorized{}
}

/*
	GetBuildOutputUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type GetBuildOutputUnauthorized struct {
	Payload *models.JSONError
}

func (o *GetBuildOutputUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/build-output/{id}][%d] getBuildOutputUnauthorized  %+v", 401, o.Payload)
}
func (o *GetBuildOutputUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildOutputUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildOutputNotFound creates a GetBuildOutputNotFound with default headers values
func NewGetBuildOutputNotFound() *GetBuildOutputNotFound {
	return &GetBuildOutputNotFound{}
}

/*
	GetBuildOutputNotFound describes a response with status code 404, with default header values.

Not found. The supplied build ID was not found.
*/
type GetBuildOutputNotFound struct {
	Payload *models.JSONError
}

func (o *GetBuildOutputNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/build-output/{id}][%d] getBuildOutputNotFound  %+v", 404, o.Payload)
}
func (o *GetBuildOutputNotFound) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildOutputNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildOutputInternalServerError creates a GetBuildOutputInternalServerError with default headers values
func NewGetBuildOutputInternalServerError() *GetBuildOutputInternalServerError {
	return &GetBuildOutputInternalServerError{}
}

/*
	GetBuildOutputInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetBuildOutputInternalServerError struct {
	Payload *models.JSONError
}

func (o *GetBuildOutputInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/build-output/{id}][%d] getBuildOutputInternalServerError  %+v", 500, o.Payload)
}
func (o *GetBuildOutputInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildOutputInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
