// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// GetBuildReader is a Reader for the GetBuild structure.
type GetBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBuildOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBuildBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetBuildUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBuildNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBuildInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBuildOK creates a GetBuildOK with default headers values
func NewGetBuildOK() *GetBuildOK {
	return &GetBuildOK{}
}

/*
	GetBuildOK describes a response with status code 200, with default header values.

Success.
*/
type GetBuildOK struct {
	Payload *models.BuildMetadataResponse
}

func (o *GetBuildOK) Error() string {
	return fmt.Sprintf("[GET /v1/build/{id}][%d] getBuildOK  %+v", 200, o.Payload)
}
func (o *GetBuildOK) GetPayload() *models.BuildMetadataResponse {
	return o.Payload
}

func (o *GetBuildOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BuildMetadataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildBadRequest creates a GetBuildBadRequest with default headers values
func NewGetBuildBadRequest() *GetBuildBadRequest {
	return &GetBuildBadRequest{}
}

/*
	GetBuildBadRequest describes a response with status code 400, with default header values.

Bad request. Ensure build ID is properly formatted.
*/
type GetBuildBadRequest struct {
	Payload *models.JSONError
}

func (o *GetBuildBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/build/{id}][%d] getBuildBadRequest  %+v", 400, o.Payload)
}
func (o *GetBuildBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildUnauthorized creates a GetBuildUnauthorized with default headers values
func NewGetBuildUnauthorized() *GetBuildUnauthorized {
	return &GetBuildUnauthorized{}
}

/*
	GetBuildUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type GetBuildUnauthorized struct {
	Payload *models.JSONError
}

func (o *GetBuildUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/build/{id}][%d] getBuildUnauthorized  %+v", 401, o.Payload)
}
func (o *GetBuildUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildNotFound creates a GetBuildNotFound with default headers values
func NewGetBuildNotFound() *GetBuildNotFound {
	return &GetBuildNotFound{}
}

/*
	GetBuildNotFound describes a response with status code 404, with default header values.

Not found. The supplied build ID was not found.
*/
type GetBuildNotFound struct {
	Payload *models.JSONError
}

func (o *GetBuildNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/build/{id}][%d] getBuildNotFound  %+v", 404, o.Payload)
}
func (o *GetBuildNotFound) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildInternalServerError creates a GetBuildInternalServerError with default headers values
func NewGetBuildInternalServerError() *GetBuildInternalServerError {
	return &GetBuildInternalServerError{}
}

/*
	GetBuildInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetBuildInternalServerError struct {
	Payload *models.JSONError
}

func (o *GetBuildInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/build/{id}][%d] getBuildInternalServerError  %+v", 500, o.Payload)
}
func (o *GetBuildInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
