// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBuildStatsParams creates a new GetBuildStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBuildStatsParams() *GetBuildStatsParams {
	return &GetBuildStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBuildStatsParamsWithTimeout creates a new GetBuildStatsParams object
// with the ability to set a timeout on a request.
func NewGetBuildStatsParamsWithTimeout(timeout time.Duration) *GetBuildStatsParams {
	return &GetBuildStatsParams{
		timeout: timeout,
	}
}

// NewGetBuildStatsParamsWithContext creates a new GetBuildStatsParams object
// with the ability to set a context for a request.
func NewGetBuildStatsParamsWithContext(ctx context.Context) *GetBuildStatsParams {
	return &GetBuildStatsParams{
		Context: ctx,
	}
}

// NewGetBuildStatsParamsWithHTTPClient creates a new GetBuildStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBuildStatsParamsWithHTTPClient(client *http.Client) *GetBuildStatsParams {
	return &GetBuildStatsParams{
		HTTPClient: client,
	}
}

/* GetBuildStatsParams contains all the parameters to send to the API endpoint
   for the get build stats operation.

   Typically these are written to a http.Request.
*/
type GetBuildStatsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get build stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildStatsParams) WithDefaults() *GetBuildStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get build stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get build stats params
func (o *GetBuildStatsParams) WithTimeout(timeout time.Duration) *GetBuildStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get build stats params
func (o *GetBuildStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get build stats params
func (o *GetBuildStatsParams) WithContext(ctx context.Context) *GetBuildStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get build stats params
func (o *GetBuildStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get build stats params
func (o *GetBuildStatsParams) WithHTTPClient(client *http.Client) *GetBuildStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get build stats params
func (o *GetBuildStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBuildStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
