// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// GetBuildStatsReader is a Reader for the GetBuildStats structure.
type GetBuildStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBuildStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBuildStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBuildStatsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetBuildStatsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBuildStatsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBuildStatsOK creates a GetBuildStatsOK with default headers values
func NewGetBuildStatsOK() *GetBuildStatsOK {
	return &GetBuildStatsOK{}
}

/*
	GetBuildStatsOK describes a response with status code 200, with default header values.

Success.
*/
type GetBuildStatsOK struct {
	Payload *models.BuildStatsResponse
}

func (o *GetBuildStatsOK) Error() string {
	return fmt.Sprintf("[GET /v1/stats/builds][%d] getBuildStatsOK  %+v", 200, o.Payload)
}
func (o *GetBuildStatsOK) GetPayload() *models.BuildStatsResponse {
	return o.Payload
}

func (o *GetBuildStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BuildStatsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildStatsUnauthorized creates a GetBuildStatsUnauthorized with default headers values
func NewGetBuildStatsUnauthorized() *GetBuildStatsUnauthorized {
	return &GetBuildStatsUnauthorized{}
}

/*
	GetBuildStatsUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type GetBuildStatsUnauthorized struct {
	Payload *models.JSONError
}

func (o *GetBuildStatsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/stats/builds][%d] getBuildStatsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetBuildStatsUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildStatsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildStatsForbidden creates a GetBuildStatsForbidden with default headers values
func NewGetBuildStatsForbidden() *GetBuildStatsForbidden {
	return &GetBuildStatsForbidden{}
}

/*
	GetBuildStatsForbidden describes a response with status code 403, with default header values.

Authorization token does not contain the Build Service Admin role.
*/
type GetBuildStatsForbidden struct {
	Payload *models.JSONError
}

func (o *GetBuildStatsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/stats/builds][%d] getBuildStatsForbidden  %+v", 403, o.Payload)
}
func (o *GetBuildStatsForbidden) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildStatsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildStatsInternalServerError creates a GetBuildStatsInternalServerError with default headers values
func NewGetBuildStatsInternalServerError() *GetBuildStatsInternalServerError {
	return &GetBuildStatsInternalServerError{}
}

/*
	GetBuildStatsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetBuildStatsInternalServerError struct {
	Payload *models.JSONError
}

func (o *GetBuildStatsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/stats/builds][%d] getBuildStatsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetBuildStatsInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildStatsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
