// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBuildsParams creates a new GetBuildsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBuildsParams() *GetBuildsParams {
	return &GetBuildsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBuildsParamsWithTimeout creates a new GetBuildsParams object
// with the ability to set a timeout on a request.
func NewGetBuildsParamsWithTimeout(timeout time.Duration) *GetBuildsParams {
	return &GetBuildsParams{
		timeout: timeout,
	}
}

// NewGetBuildsParamsWithContext creates a new GetBuildsParams object
// with the ability to set a context for a request.
func NewGetBuildsParamsWithContext(ctx context.Context) *GetBuildsParams {
	return &GetBuildsParams{
		Context: ctx,
	}
}

// NewGetBuildsParamsWithHTTPClient creates a new GetBuildsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBuildsParamsWithHTTPClient(client *http.Client) *GetBuildsParams {
	return &GetBuildsParams{
		HTTPClient: client,
	}
}

/* GetBuildsParams contains all the parameters to send to the API endpoint
   for the get builds operation.

   Typically these are written to a http.Request.
*/
type GetBuildsParams struct {

	/* From.

	   an RFC 3339 date and time string specifying the earliest build date and time to include in results
	*/
	From *string

	/* IncludeDeleted.

	   true/false to specify whether query deleted builds
	*/
	IncludeDeleted *string

	/* To.

	   an RFC 3339 date and time string specifying the latest build date and time to include in results
	*/
	To *string

	/* User.

	   a user primitive.ObjectID, specifies the user search condition
	*/
	User *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get builds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildsParams) WithDefaults() *GetBuildsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get builds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get builds params
func (o *GetBuildsParams) WithTimeout(timeout time.Duration) *GetBuildsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get builds params
func (o *GetBuildsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get builds params
func (o *GetBuildsParams) WithContext(ctx context.Context) *GetBuildsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get builds params
func (o *GetBuildsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get builds params
func (o *GetBuildsParams) WithHTTPClient(client *http.Client) *GetBuildsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get builds params
func (o *GetBuildsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the get builds params
func (o *GetBuildsParams) WithFrom(from *string) *GetBuildsParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get builds params
func (o *GetBuildsParams) SetFrom(from *string) {
	o.From = from
}

// WithIncludeDeleted adds the includeDeleted to the get builds params
func (o *GetBuildsParams) WithIncludeDeleted(includeDeleted *string) *GetBuildsParams {
	o.SetIncludeDeleted(includeDeleted)
	return o
}

// SetIncludeDeleted adds the includeDeleted to the get builds params
func (o *GetBuildsParams) SetIncludeDeleted(includeDeleted *string) {
	o.IncludeDeleted = includeDeleted
}

// WithTo adds the to to the get builds params
func (o *GetBuildsParams) WithTo(to *string) *GetBuildsParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get builds params
func (o *GetBuildsParams) SetTo(to *string) {
	o.To = to
}

// WithUser adds the user to the get builds params
func (o *GetBuildsParams) WithUser(user *string) *GetBuildsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get builds params
func (o *GetBuildsParams) SetUser(user *string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *GetBuildsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.IncludeDeleted != nil {

		// query param includeDeleted
		var qrIncludeDeleted string

		if o.IncludeDeleted != nil {
			qrIncludeDeleted = *o.IncludeDeleted
		}
		qIncludeDeleted := qrIncludeDeleted
		if qIncludeDeleted != "" {

			if err := r.SetQueryParam("includeDeleted", qIncludeDeleted); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if o.User != nil {

		// query param user
		var qrUser string

		if o.User != nil {
			qrUser = *o.User
		}
		qUser := qrUser
		if qUser != "" {

			if err := r.SetQueryParam("user", qUser); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
