// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/buildserver/models"
)

// GetBuildsReader is a Reader for the GetBuilds structure.
type GetBuildsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBuildsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBuildsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBuildsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBuildsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBuildsOK creates a GetBuildsOK with default headers values
func NewGetBuildsOK() *GetBuildsOK {
	return &GetBuildsOK{}
}

/*
	GetBuildsOK describes a response with status code 200, with default header values.

Success.
*/
type GetBuildsOK struct {
	Payload *models.ListBuildsResponse
}

func (o *GetBuildsOK) Error() string {
	return fmt.Sprintf("[GET /v1/build][%d] getBuildsOK  %+v", 200, o.Payload)
}
func (o *GetBuildsOK) GetPayload() *models.ListBuildsResponse {
	return o.Payload
}

func (o *GetBuildsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListBuildsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildsUnauthorized creates a GetBuildsUnauthorized with default headers values
func NewGetBuildsUnauthorized() *GetBuildsUnauthorized {
	return &GetBuildsUnauthorized{}
}

/*
	GetBuildsUnauthorized describes a response with status code 401, with default header values.

Authorization token was not supplied, not valid, or revoked.
*/
type GetBuildsUnauthorized struct {
	Payload *models.JSONError
}

func (o *GetBuildsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/build][%d] getBuildsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetBuildsUnauthorized) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildsInternalServerError creates a GetBuildsInternalServerError with default headers values
func NewGetBuildsInternalServerError() *GetBuildsInternalServerError {
	return &GetBuildsInternalServerError{}
}

/*
	GetBuildsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetBuildsInternalServerError struct {
	Payload *models.JSONError
}

func (o *GetBuildsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/build][%d] getBuildsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetBuildsInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *GetBuildsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
