// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// GetGroupReader is a Reader for the GetGroup structure.
type GetGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGroupOK creates a GetGroupOK with default headers values
func NewGetGroupOK() *GetGroupOK {
	return &GetGroupOK{}
}

/*
	GetGroupOK describes a response with status code 200, with default header values.

Success
*/
type GetGroupOK struct {
	Payload *models.GroupResponse
}

func (o *GetGroupOK) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups/{group}][%d] getGroupOK  %+v", 200, o.Payload)
}
func (o *GetGroupOK) GetPayload() *models.GroupResponse {
	return o.Payload
}

func (o *GetGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupBadRequest creates a GetGroupBadRequest with default headers values
func NewGetGroupBadRequest() *GetGroupBadRequest {
	return &GetGroupBadRequest{}
}

/*
	GetGroupBadRequest describes a response with status code 400, with default header values.

Bad request - group name not valid
*/
type GetGroupBadRequest struct {
	Payload *models.Json400error
}

func (o *GetGroupBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups/{group}][%d] getGroupBadRequest  %+v", 400, o.Payload)
}
func (o *GetGroupBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *GetGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupUnauthorized creates a GetGroupUnauthorized with default headers values
func NewGetGroupUnauthorized() *GetGroupUnauthorized {
	return &GetGroupUnauthorized{}
}

/*
	GetGroupUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type GetGroupUnauthorized struct {
	Payload *models.Json401error
}

func (o *GetGroupUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups/{group}][%d] getGroupUnauthorized  %+v", 401, o.Payload)
}
func (o *GetGroupUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *GetGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupNotFound creates a GetGroupNotFound with default headers values
func NewGetGroupNotFound() *GetGroupNotFound {
	return &GetGroupNotFound{}
}

/*
	GetGroupNotFound describes a response with status code 404, with default header values.

Bad request - group name not found
*/
type GetGroupNotFound struct {
	Payload *models.Json404error
}

func (o *GetGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups/{group}][%d] getGroupNotFound  %+v", 404, o.Payload)
}
func (o *GetGroupNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *GetGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupInternalServerError creates a GetGroupInternalServerError with default headers values
func NewGetGroupInternalServerError() *GetGroupInternalServerError {
	return &GetGroupInternalServerError{}
}

/*
	GetGroupInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetGroupInternalServerError struct {
	Payload *models.Json500error
}

func (o *GetGroupInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups/{group}][%d] getGroupInternalServerError  %+v", 500, o.Payload)
}
func (o *GetGroupInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *GetGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
