// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// GroupAddRoleReader is a Reader for the GroupAddRole structure.
type GroupAddRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupAddRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupAddRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGroupAddRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGroupAddRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGroupAddRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGroupAddRoleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupAddRoleOK creates a GroupAddRoleOK with default headers values
func NewGroupAddRoleOK() *GroupAddRoleOK {
	return &GroupAddRoleOK{}
}

/*
	GroupAddRoleOK describes a response with status code 200, with default header values.

Success
*/
type GroupAddRoleOK struct {
	Payload *models.GroupResponse
}

func (o *GroupAddRoleOK) Error() string {
	return fmt.Sprintf("[POST /v1/admin/groups/{group}/role/{role}][%d] groupAddRoleOK  %+v", 200, o.Payload)
}
func (o *GroupAddRoleOK) GetPayload() *models.GroupResponse {
	return o.Payload
}

func (o *GroupAddRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupAddRoleBadRequest creates a GroupAddRoleBadRequest with default headers values
func NewGroupAddRoleBadRequest() *GroupAddRoleBadRequest {
	return &GroupAddRoleBadRequest{}
}

/*
	GroupAddRoleBadRequest describes a response with status code 400, with default header values.

Bad request - group or role not valid
*/
type GroupAddRoleBadRequest struct {
	Payload *models.Json400error
}

func (o *GroupAddRoleBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/admin/groups/{group}/role/{role}][%d] groupAddRoleBadRequest  %+v", 400, o.Payload)
}
func (o *GroupAddRoleBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *GroupAddRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupAddRoleUnauthorized creates a GroupAddRoleUnauthorized with default headers values
func NewGroupAddRoleUnauthorized() *GroupAddRoleUnauthorized {
	return &GroupAddRoleUnauthorized{}
}

/*
	GroupAddRoleUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type GroupAddRoleUnauthorized struct {
	Payload *models.Json401error
}

func (o *GroupAddRoleUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/admin/groups/{group}/role/{role}][%d] groupAddRoleUnauthorized  %+v", 401, o.Payload)
}
func (o *GroupAddRoleUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *GroupAddRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupAddRoleNotFound creates a GroupAddRoleNotFound with default headers values
func NewGroupAddRoleNotFound() *GroupAddRoleNotFound {
	return &GroupAddRoleNotFound{}
}

/*
	GroupAddRoleNotFound describes a response with status code 404, with default header values.

Bad request - group not found
*/
type GroupAddRoleNotFound struct {
	Payload *models.Json404error
}

func (o *GroupAddRoleNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/admin/groups/{group}/role/{role}][%d] groupAddRoleNotFound  %+v", 404, o.Payload)
}
func (o *GroupAddRoleNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *GroupAddRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupAddRoleInternalServerError creates a GroupAddRoleInternalServerError with default headers values
func NewGroupAddRoleInternalServerError() *GroupAddRoleInternalServerError {
	return &GroupAddRoleInternalServerError{}
}

/*
	GroupAddRoleInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GroupAddRoleInternalServerError struct {
	Payload *models.Json500error
}

func (o *GroupAddRoleInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/admin/groups/{group}/role/{role}][%d] groupAddRoleInternalServerError  %+v", 500, o.Payload)
}
func (o *GroupAddRoleInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *GroupAddRoleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
