// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// GroupRemoveRoleReader is a Reader for the GroupRemoveRole structure.
type GroupRemoveRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupRemoveRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupRemoveRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGroupRemoveRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGroupRemoveRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGroupRemoveRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGroupRemoveRoleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupRemoveRoleOK creates a GroupRemoveRoleOK with default headers values
func NewGroupRemoveRoleOK() *GroupRemoveRoleOK {
	return &GroupRemoveRoleOK{}
}

/*
	GroupRemoveRoleOK describes a response with status code 200, with default header values.

Success
*/
type GroupRemoveRoleOK struct {
	Payload *models.GroupResponse
}

func (o *GroupRemoveRoleOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/groups/{group}/role/{role}][%d] groupRemoveRoleOK  %+v", 200, o.Payload)
}
func (o *GroupRemoveRoleOK) GetPayload() *models.GroupResponse {
	return o.Payload
}

func (o *GroupRemoveRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupRemoveRoleBadRequest creates a GroupRemoveRoleBadRequest with default headers values
func NewGroupRemoveRoleBadRequest() *GroupRemoveRoleBadRequest {
	return &GroupRemoveRoleBadRequest{}
}

/*
	GroupRemoveRoleBadRequest describes a response with status code 400, with default header values.

Bad request - group or role not valid
*/
type GroupRemoveRoleBadRequest struct {
	Payload *models.Json400error
}

func (o *GroupRemoveRoleBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/groups/{group}/role/{role}][%d] groupRemoveRoleBadRequest  %+v", 400, o.Payload)
}
func (o *GroupRemoveRoleBadRequest) GetPayload() *models.Json400error {
	return o.Payload
}

func (o *GroupRemoveRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json400error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupRemoveRoleUnauthorized creates a GroupRemoveRoleUnauthorized with default headers values
func NewGroupRemoveRoleUnauthorized() *GroupRemoveRoleUnauthorized {
	return &GroupRemoveRoleUnauthorized{}
}

/*
	GroupRemoveRoleUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type GroupRemoveRoleUnauthorized struct {
	Payload *models.Json401error
}

func (o *GroupRemoveRoleUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/groups/{group}/role/{role}][%d] groupRemoveRoleUnauthorized  %+v", 401, o.Payload)
}
func (o *GroupRemoveRoleUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *GroupRemoveRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupRemoveRoleNotFound creates a GroupRemoveRoleNotFound with default headers values
func NewGroupRemoveRoleNotFound() *GroupRemoveRoleNotFound {
	return &GroupRemoveRoleNotFound{}
}

/*
	GroupRemoveRoleNotFound describes a response with status code 404, with default header values.

Bad request - group not found
*/
type GroupRemoveRoleNotFound struct {
	Payload *models.Json404error
}

func (o *GroupRemoveRoleNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/groups/{group}/role/{role}][%d] groupRemoveRoleNotFound  %+v", 404, o.Payload)
}
func (o *GroupRemoveRoleNotFound) GetPayload() *models.Json404error {
	return o.Payload
}

func (o *GroupRemoveRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json404error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupRemoveRoleInternalServerError creates a GroupRemoveRoleInternalServerError with default headers values
func NewGroupRemoveRoleInternalServerError() *GroupRemoveRoleInternalServerError {
	return &GroupRemoveRoleInternalServerError{}
}

/*
	GroupRemoveRoleInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GroupRemoveRoleInternalServerError struct {
	Payload *models.Json500error
}

func (o *GroupRemoveRoleInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/admin/groups/{group}/role/{role}][%d] groupRemoveRoleInternalServerError  %+v", 500, o.Payload)
}
func (o *GroupRemoveRoleInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *GroupRemoveRoleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
