// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGroupAddRoleParams creates a new GroupAddRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupAddRoleParams() *GroupAddRoleParams {
	return &GroupAddRoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupAddRoleParamsWithTimeout creates a new GroupAddRoleParams object
// with the ability to set a timeout on a request.
func NewGroupAddRoleParamsWithTimeout(timeout time.Duration) *GroupAddRoleParams {
	return &GroupAddRoleParams{
		timeout: timeout,
	}
}

// NewGroupAddRoleParamsWithContext creates a new GroupAddRoleParams object
// with the ability to set a context for a request.
func NewGroupAddRoleParamsWithContext(ctx context.Context) *GroupAddRoleParams {
	return &GroupAddRoleParams{
		Context: ctx,
	}
}

// NewGroupAddRoleParamsWithHTTPClient creates a new GroupAddRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupAddRoleParamsWithHTTPClient(client *http.Client) *GroupAddRoleParams {
	return &GroupAddRoleParams{
		HTTPClient: client,
	}
}

/* GroupAddRoleParams contains all the parameters to send to the API endpoint
   for the group add role operation.

   Typically these are written to a http.Request.
*/
type GroupAddRoleParams struct {

	/* Group.

	   Name of group to add to role
	*/
	Group string

	/* Role.

	   Name of role
	*/
	Role string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the group add role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupAddRoleParams) WithDefaults() *GroupAddRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the group add role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupAddRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the group add role params
func (o *GroupAddRoleParams) WithTimeout(timeout time.Duration) *GroupAddRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group add role params
func (o *GroupAddRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group add role params
func (o *GroupAddRoleParams) WithContext(ctx context.Context) *GroupAddRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group add role params
func (o *GroupAddRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group add role params
func (o *GroupAddRoleParams) WithHTTPClient(client *http.Client) *GroupAddRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group add role params
func (o *GroupAddRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the group add role params
func (o *GroupAddRoleParams) WithGroup(group string) *GroupAddRoleParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the group add role params
func (o *GroupAddRoleParams) SetGroup(group string) {
	o.Group = group
}

// WithRole adds the role to the group add role params
func (o *GroupAddRoleParams) WithRole(role string) *GroupAddRoleParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the group add role params
func (o *GroupAddRoleParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a swagger request
func (o *GroupAddRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group
	if err := r.SetPathParam("group", o.Group); err != nil {
		return err
	}

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
