// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sylabs/singularity/v4/enterprise-plugin/pkg/consentservice/models"
)

// ListGroupsReader is a Reader for the ListGroups structure.
type ListGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListGroupsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListGroupsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListGroupsOK creates a ListGroupsOK with default headers values
func NewListGroupsOK() *ListGroupsOK {
	return &ListGroupsOK{}
}

/*
	ListGroupsOK describes a response with status code 200, with default header values.

Success
*/
type ListGroupsOK struct {
	Payload *models.GroupListResponse
}

func (o *ListGroupsOK) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups][%d] listGroupsOK  %+v", 200, o.Payload)
}
func (o *ListGroupsOK) GetPayload() *models.GroupListResponse {
	return o.Payload
}

func (o *ListGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListGroupsUnauthorized creates a ListGroupsUnauthorized with default headers values
func NewListGroupsUnauthorized() *ListGroupsUnauthorized {
	return &ListGroupsUnauthorized{}
}

/*
	ListGroupsUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type ListGroupsUnauthorized struct {
	Payload *models.Json401error
}

func (o *ListGroupsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups][%d] listGroupsUnauthorized  %+v", 401, o.Payload)
}
func (o *ListGroupsUnauthorized) GetPayload() *models.Json401error {
	return o.Payload
}

func (o *ListGroupsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json401error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListGroupsInternalServerError creates a ListGroupsInternalServerError with default headers values
func NewListGroupsInternalServerError() *ListGroupsInternalServerError {
	return &ListGroupsInternalServerError{}
}

/*
	ListGroupsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ListGroupsInternalServerError struct {
	Payload *models.Json500error
}

func (o *ListGroupsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/admin/groups][%d] listGroupsInternalServerError  %+v", 500, o.Payload)
}
func (o *ListGroupsInternalServerError) GetPayload() *models.Json500error {
	return o.Payload
}

func (o *ListGroupsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Json500error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
