// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListGroupsParams creates a new ListGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListGroupsParams() *ListGroupsParams {
	return &ListGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListGroupsParamsWithTimeout creates a new ListGroupsParams object
// with the ability to set a timeout on a request.
func NewListGroupsParamsWithTimeout(timeout time.Duration) *ListGroupsParams {
	return &ListGroupsParams{
		timeout: timeout,
	}
}

// NewListGroupsParamsWithContext creates a new ListGroupsParams object
// with the ability to set a context for a request.
func NewListGroupsParamsWithContext(ctx context.Context) *ListGroupsParams {
	return &ListGroupsParams{
		Context: ctx,
	}
}

// NewListGroupsParamsWithHTTPClient creates a new ListGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListGroupsParamsWithHTTPClient(client *http.Client) *ListGroupsParams {
	return &ListGroupsParams{
		HTTPClient: client,
	}
}

/* ListGroupsParams contains all the parameters to send to the API endpoint
   for the list groups operation.

   Typically these are written to a http.Request.
*/
type ListGroupsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListGroupsParams) WithDefaults() *ListGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list groups params
func (o *ListGroupsParams) WithTimeout(timeout time.Duration) *ListGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list groups params
func (o *ListGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list groups params
func (o *ListGroupsParams) WithContext(ctx context.Context) *ListGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list groups params
func (o *ListGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list groups params
func (o *ListGroupsParams) WithHTTPClient(client *http.Client) *ListGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list groups params
func (o *ListGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
